
---
title: "uBiome Oral Health Outcomes"
author: "Chirag Patel"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(tidyverse)
library(DBI)
library(survey)
library(tictoc)
devtools::load_all(".")
```



```{r}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/nhanes_112824.sqlite') ## path to the sqlite 
table_description <- tbl(con, "table_names_epcf")
variable_description <- tbl(con, "variable_names_epcf")
```


# Oral health
- OHXREF_F
- OHXREF_G
```{r}
oral_outcome_tab <- function(con, table_name="OHXREF_F") {
  ## encode outcomes
  oh <- tbl(con, table_name) |> collect()
  oh <- oh |> mutate(
  TOOTH_DECAY_OHAROCDT = case_when(
    OHAROCDT == 1 ~ 1,
    OHDEXSTS == 1 ~ 0,
    TRUE ~ NA_integer_
  ),
  
  GUM_DISEASE_OHAROCGP = case_when(
    OHAROCGP == 1 ~ 1,
    OHDEXSTS == 1 ~ 0,
    TRUE ~ NA_integer_
  ),
  
  ORAL_HYGIENE_OHAROCOH = case_when(
    OHAROCOH == 1 ~ 1,
    OHDEXSTS == 1 ~ 0,
    TRUE ~ NA_integer_
  ),
  
  DENTURE_OHAROCDE = case_when(
    OHAROCDE == 1 ~ 1,
    OHDEXSTS == 1 ~ 0,
    TRUE ~ NA_integer_
  )
  )
}

#ohx_f <- tbl(con, "OHXREF_F")
oh_f <- oral_outcome_tab(con, "OHXREF_F")
oh_g <- oral_outcome_tab(con, "OHXREF_G")
#ohx_g <- tbl(con, "OHXREF_G")
```

Upload
```{r}

# TOOTH_DECAY_OHAROCDT
# DENTURE_OHAROCDE
# ORAL_HYGIENE_OHAROCOH
# GUM_DISEASE_OHAROCGP

outcome_oh_f <- oh_f |> select(SEQN, TOOTH_DECAY_OHAROCDT,DENTURE_OHAROCDE, ORAL_HYGIENE_OHAROCOH,GUM_DISEASE_OHAROCGP)
outcome_oh_g <- oh_g |> select(SEQN, TOOTH_DECAY_OHAROCDT,DENTURE_OHAROCDE, ORAL_HYGIENE_OHAROCOH,GUM_DISEASE_OHAROCGP)

dbWriteTable(con, "d_outcome_oh_f", outcome_oh_f,overwrite=T) # derived outcome
dbWriteTable(con, "d_outcome_oh_g", outcome_oh_g,overwrite=T) # derived outcome 
```


```{r}
new_tabs <- tibble(Data.File.Name = c("d_outcome_oh_f", "d_outcome_oh_g"), 
                   component=c("EXAM", "EXAM"),
                   series = c("F", "G"),
                   epcf = c("p", "p")
                  )

new_vars_f <- tibble(Variable.Name = c("TOOTH_DECAY_OHAROCDT", "DENTURE_OHAROCDE",
                                     "ORAL_HYGIENE_OHAROCOH","GUM_DISEASE_OHAROCGP"), 
                   Variable.Description = c("Tooth Decay", "Denture", "Oral Hygiene", "Gum Disease"),
                   Use.Constraints = c("None", "None", "None", "None"),
                   Data.File.Name = "d_outcome_oh_f",
                   Data.File.Description = "Derived Oral Health Outcome",
                   Begin.Year = 2009,
                   EndYear = 2010,
                   Component = "Examination"
                  )
new_vars_g <- tibble(Variable.Name = c("TOOTH_DECAY_OHAROCDT", "DENTURE_OHAROCDE",
                                     "ORAL_HYGIENE_OHAROCOH","GUM_DISEASE_OHAROCGP"), 
                   Variable.Description = c("Tooth Decay", "Denture", "Oral Hygiene", "Gum Disease"),
                   Use.Constraints = c("None", "None", "None", "None"),
                   Data.File.Name = "d_outcome_oh_g",
                   Data.File.Description = "Derived Oral Health Outcome",
                   Begin.Year = 2011,
                   EndYear = 2012,
                   Component = "Examination"
                  )

new_vars <- rbind(new_vars_f, new_vars_g)

table_description_lcl <- table_description |> collect() |> rbind(new_tabs)
variable_description_lcl <- variable_description |> collect() |> rbind(new_vars)

dbWriteTable(con, "table_names_epcf", table_description_lcl, overwrite=T)
dbWriteTable(con, "variable_names_epcf", variable_description_lcl, overwrite=T)
```


Test
```{r}
devtools::load_all("..")
use_models <- adjustment_models |> filter(scenario == "base" | scenario == 'age_sex_ethnicity_income_education')
test <- logistic_e_flex_adjust("TOOTH_DECAY_OHAROCDT", "LBXCOT", adjustment_variables = use_models,con,logxform_e=T, scale_e=T)


test <- logistic_e_flex_adjust("TOOTH_DECAY_OHAROCDT", "RSV_genus519_relative", adjustment_variables = use_models,con,logxform_e=T, scale_e=T)

```
