---
title: "0_cfd.Rmd"
author: "Chirag Patel"
date: "2025-12-28"
output: html_document
---

Create a merged summary stats similar to the adjusted_meta.Rdata

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
load('./adjusted_meta_2.Rdata')
exposure_desc  <- adjusted_meta_2 |> select(evarname, evardesc, esubcategory, enewsubcategory, super_ecat_number) |> unique()

cfdds <- read_rds("../pe_summary_0824/CFDDS.rds")
summary_stats <- cfdds$pe_tidied |> filter(model_number == 2) |> filter(grepl("expo", term)) |> rename(evarname=exposure, pvarname=phenotype)
summary_stats <- summary_stats |> left_join(exposure_desc , by="evarname")

summary_stats <- summary_stats |> filter(evarname != "H0Q065") |> filter(evarname != 'PAQ_recreation_vigorous_week')
summary_stats <- summary_stats |> mutate(evardesc = ifelse(evarname == 'PAQ_recreation_vigorous_met', "Vigorous Activity METs", evardesc))
summary_stats <- summary_stats |> mutate(evardesc = ifelse(evarname == 'PAQ_total_met', "Total Activity METs", evardesc))

uni_rsq <- cfdds$rsq |> filter(model_number==2, aggregate_base_model==T) |> select(rsq, model_number, exposure) |> rename(ursq=rsq)
full_rsq <- cfdds$rsq |> filter(model_number==2, aggregate_base_model==F)  |> select(rsq, model_number, exposure) |> rename(frsq=rsq)
rsq <- full_rsq |> left_join(uni_rsq, by="exposure")  |> mutate(rsq_diff=frsq-ursq) |> select(-model_number.x, -model_number.y) |> rename(evarname=exposure)

summary_stats <- summary_stats |> left_join(rsq) |> rename(rsq_adjusted_base_diff=rsq_diff)
summary_stats <- summary_stats |> mutate(nobs=2) |> rename(term_name=term)
summary_stats |> write_rds("./adjusted_meta_cfq.rds")
```