---
title: "1.Rmd"
author: "Chirag Patel"
date: "2025-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Create data resources for package, e.g., the catalogs for the package
2. Output the summary statistics as .csv and place it into ./papers_figures_tables


```{r}
library(tidyverse)
load('adjusted_meta_2.Rdata')
```

# Write out for Supplementary Table
```{r}
adjusted_meta_2 |> write_csv(file = "./paper_figures_tables/summary_stats.csv")
```
# Prepare e and p variables for the catalog for the package user

```{r catalog to data folder}
p_catalog <- adjusted_meta_2 |> select(pvarname, pnewsubcategory, pvardesc) |> unique() |> rename(pcategory=pnewsubcategory)
e_catalog <- adjusted_meta_2 |> select(evarname, super_ecat_name, enewsubcategory, evardesc) |> unique()
#usethis::use_data(p_catalog)
#usethis::use_data(e_catalog)

p_catalog |> write_csv("./paper_figures_tables/p_catalog.csv")
e_catalog |> write_csv("./paper_figures_tables/e_catalog.csv")

```


```{r}
adjusted_meta_2 |> group_by(sig_levels) |> count()
adjusted_meta_2 |> group_by(pvarname) |> count() |> ungroup() |> summarize(min(n), max(n), median(n))
tot <- adjusted_meta_2 |> group_by(pvarname) |> count() |> ungroup() |> rename(total=n)
adjusted_meta_2 |> group_by(pvarname, sig_levels) |> count() |> ungroup() |> left_join(tot) |> mutate(pct_sig = n/total) |> filter(sig_levels == 'Bonf.<0.05') |> summarize(min(pct_sig*100), max(pct_sig*100))
adjusted_meta_2 |> group_by(pvarname, sig_levels) |> count() |> ungroup() |> left_join(tot) |> mutate(pct_sig = n/total) |> filter(sig_levels == 'Bonf.<0.05') |> arrange(-pct_sig)

```
