---
title: "arch.Rmd"
author: "Chirag Patel"
date: "2025-03-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(DBI)
library(ggsci)
library(DT)
library(ggrepel)
library(cowplot)
library(reactable)
library(gt)
library(broom)
library(ggridges)
library(ComplexHeatmap)
library(circlize)
library(corrr)
```

```{r}
load('./adjusted_meta_2.Rdata')
```

```{r}
super_ecat_colors <- tibble(ecat_name = c(
  "Dietary Interview+Behavior",
  "Smoking+Hydrocarbon+Metals",
  "Consumables",
  "Pollutants",
  "Volatile Organics",
  "Infection"
), colors=pal_observable()(6))

super_pcat_colors <- tibble(pcat_name=c(
  "aging",
  "anthropometric",
  "lung",
  "fitness",
  "blood pressure",
  "biochemistry",
  "blood",
  "microbiome"
), colors=pal_observable()(8))

pnewcat_colors <- tibble(pnewsubcategory = c(
  'aging',
  'anthropometric', 
  'metabolic',
  'lipids',
  'liver',
  'hormone',
  'nutrition',
  'kidney',
  'electrolyte',
  'fitness',
  'blood pressure',
  'blood', 
  'inflammation',
  'iron', 
  'lung',
  'bone',
  'microbiome',
  'psa'
),
  pnewcat_order = 1:18,
  colors=rep(c('#4269D0FF', '#EFB118FF', '#FF725CFF'), 6)
)

```

Filter for visualization
```{r}
adjusted_meta_to_hm <- adjusted_meta_2 |> filter(pnewsubcategory != 'dexa' ) |> filter(pnewsubcategory != 'microbiome' )

adjusted_meta_to_hm <-  adjusted_meta_to_hm |> rbind(adjusted_meta_2 |> filter(grepl("^RSV", pvarname)))


```


```{r}
adjusted_meta_2 |> group_by(sig_levels) |> summarize(q5=quantile(estimate_overall, probs=c(.05)), q95=quantile(estimate_overall, probs=.95))
adjusted_meta_2 |> group_by(sig_levels) |> summarize(q5=quantile(abs(estimate_overall), probs=c(.05)), q95=quantile(abs(estimate_overall), probs=.95))

adjusted_meta_2 |> filter(term_name == 'expo1') |> group_by(sig_levels) |> summarize(q5=quantile(estimate_overall, probs=c(.05)), q95=quantile(estimate_overall, probs=.95))


```

ExP Map
```{r r2 architecture}
to_array_pe <- adjusted_meta_to_hm |> filter(term_name == 'expo' | term_name == 'expo1') |> select(evarname, pvarname, estimate_overall, rsq_adjusted_base_diff, p.value_overall) |> 
  mutate(estimate_overall= ifelse(p.value_overall >= 0.1, 0, estimate_overall)) |> 
  mutate(estimate_overall = ifelse(is.na(estimate_overall), 0, estimate_overall))  |> 
  mutate(rsq_adjusted_base_diff = ifelse(is.na(rsq_adjusted_base_diff), 0, rsq_adjusted_base_diff))  |> 
  mutate(rsq_adjusted_base_diff = sign(estimate_overall)*rsq_adjusted_base_diff)  |> 
  select(-p.value_overall) |> 
  select(-estimate_overall) |>
  pivot_wider(names_from = pvarname, values_from = rsq_adjusted_base_diff)

col_fun = colorRamp2(c(-.01, 0, .01), c("blue", "white", "red"))
to_array_pe <- to_array_pe |> as.data.frame() 
rownames(to_array_pe)  <- to_array_pe$evarname
to_array_pe <- to_array_pe |> select(-evarname) |> as.matrix()
Heatmap(to_array_pe, col = col_fun, show_row_names = F, show_column_names = F)
```

```{r linear beta architecture}
to_array_pe <- adjusted_meta_to_hm |> filter(term_name == 'expo' | term_name == 'expo1') |> select(evarname, pvarname, estimate_overall, rsq_adjusted_base_diff, p.value_overall) |> 
  mutate(estimate_overall= ifelse(p.value_overall >= 0.1, 0, estimate_overall)) |> 
  mutate(estimate_overall = ifelse(is.na(estimate_overall), 0, estimate_overall))  |> 
  mutate(rsq_adjusted_base_diff = ifelse(is.na(rsq_adjusted_base_diff), 0, rsq_adjusted_base_diff))  |> 
  mutate(rsq_adjusted_base_diff = sign(estimate_overall)*rsq_adjusted_base_diff)  |> 
  select(-p.value_overall) |> 
  select(-rsq_adjusted_base_diff) |>
  pivot_wider(names_from = pvarname, values_from = estimate_overall)

rownames(to_array_pe)  <- to_array_pe$evarname


evardesc <- adjusted_meta_to_hm |> filter(term_name == 'expo' | term_name == 'expo1') |> select(evarname, ecategory, super_ecat_number,enewsubcategory, super_ecat_name) |> unique() |> as.data.frame()
pvardesc <- adjusted_meta_to_hm |> filter(term_name == 'expo' | term_name == 'expo1') |> select(pvarname, pcategory, pnewsubcategory) |> unique() |> as.data.frame()

pvardesc <- pvardesc |> left_join(pnewcat_colors, by=c("pnewsubcategory"="pnewsubcategory"))
evardesc <- evardesc |> left_join(super_ecat_colors, by=c("super_ecat_name"="ecat_name"))


rownames(evardesc) <- as.character(evardesc$evarname)
evardesc <- evardesc |> select(-evarname)
rownames(pvardesc) <- (pvardesc$pvarname)
pvardesc <- pvardesc |> select(-pvarname)

envec <- evardesc$colors
names(envec) <- evardesc$enewsubcategory
pnvec <- pvardesc$colors
names(pnvec) <- pvardesc$pnewsubcategory

rowAn = rowAnnotation(sc=evardesc$enewsubcategory, show_legend=FALSE, show_annotation_name = FALSE, col=list(sc=envec))
colAn = columnAnnotation(sc=pvardesc$pnewsubcategory, show_legend=FALSE,show_annotation_name = FALSE, col=list(sc=pnvec))
row_split_by_ecategory <- fct_reorder(
  evardesc[rownames(to_array_pe), "enewsubcategory"], 
  evardesc[rownames(to_array_pe), "super_ecat_number"])
col_split_by_pcategory <- fct_reorder(
  pvardesc[colnames(to_array_pe)[-1], "pnewsubcategory"],
  pvardesc[colnames(to_array_pe)[-1], "pnewcat_order"],
  )

to_array_pe <- to_array_pe |> select(-evarname) |> as.matrix()

```

```{r draw, fig.height=7, fig.width=7}
Heatmap(to_array_pe, left_annotation = rowAn, 
        right_annotation = rowAn, 
        top_annotation = colAn, 
        row_split = row_split_by_ecategory,
        column_split = col_split_by_pcategory,
        row_title_gp    = gpar(fontsize = 8),   # shrink/enlarge row-split label text
        row_title_rot   = 0,                    # rotate the row-split labels (default is 90)
        column_title_gp = gpar(fontsize = 8),   # shrink/enlarge column-split label text
        column_title_rot= 45,  
        show_row_names = F, show_column_names = F, cluster_columns = F, cluster_rows = F,
        name="Adjusted Beta",
        )

#pdf(file="./paper_figures_tables/atlas_fig3.pdf")
hm <- Heatmap(to_array_pe, left_annotation = rowAn, 
        right_annotation = rowAn, 
        top_annotation = colAn, 
        row_split = row_split_by_ecategory,
        column_split = col_split_by_pcategory,
        row_title_gp    = gpar(fontsize = 8),   # shrink/enlarge row-split label text
        row_title_rot   = 0,                    # rotate the row-split labels (default is 90)
        column_title_gp = gpar(fontsize = 8),   # shrink/enlarge column-split label text
        column_title_rot= 45,  
        show_row_names = F, show_column_names = F, cluster_columns = F, cluster_rows = F,
        name="Adjusted Beta",
        )
draw(hm)
dev.off()

```


```{r csv source file}
write.csv(to_array_pe, file="fig4_architecture.csv")
```

```{r}
# Nature Medicine Research Summary version
# Dimensions: 115mm x 85mm (approximately 4.5" x 3.3")

# 1. Setup dimensions
width_in <- 115 / 25.4  
height_in <- 85 / 25.4  

# 2. Filter and Process Data
adjusted_meta_compact <- adjusted_meta_to_hm |>
  filter(!pnewsubcategory %in% c("aging", "psa"))

# Rebuild the matrix 
to_array_pe_compact_df <- adjusted_meta_compact |>
  filter(term_name %in% c('expo', 'expo1')) |>
  select(evarname, pvarname, estimate_overall, p.value_overall) |>
  mutate(estimate_overall = ifelse(p.value_overall >= 0.1 | is.na(estimate_overall), 0, estimate_overall)) |>
  select(-p.value_overall) |>
  pivot_wider(names_from = pvarname, values_from = estimate_overall) |>
  as.data.frame() # Convert to DF to allow row names

rownames(to_array_pe_compact_df) <- to_array_pe_compact_df$evarname
to_array_pe_matrix <- as.matrix(to_array_pe_compact_df[, -1])

# 3. Build Annotation Data Frames
pvardesc_compact <- adjusted_meta_compact |>
  filter(term_name %in% c('expo', 'expo1')) |>
  select(pvarname, pcategory, pnewsubcategory) |>
  distinct() |>
  filter(pvarname %in% colnames(to_array_pe_matrix)) |>
  left_join(pnewcat_colors, by = "pnewsubcategory") |>
  as.data.frame()
rownames(pvardesc_compact) <- pvardesc_compact$pvarname
pvardesc_compact <- pvardesc_compact[colnames(to_array_pe_matrix), ]

evardesc_compact <- adjusted_meta_compact |>
  filter(term_name %in% c('expo', 'expo1')) |>
  select(evarname, ecategory, super_ecat_number, enewsubcategory, super_ecat_name) |>
  distinct() |>
  filter(evarname %in% rownames(to_array_pe_matrix)) |>
  left_join(super_ecat_colors, by = c("super_ecat_name" = "ecat_name")) |>
  as.data.frame()
rownames(evardesc_compact) <- evardesc_compact$evarname
evardesc_compact <- evardesc_compact[rownames(to_array_pe_matrix), ]

# 4. FIX: Named Color Vectors (The Error Fix)
envec_compact <- evardesc_compact |> 
  select(enewsubcategory, colors) |> 
  distinct() |> 
  deframe()

pnvec_compact <- pvardesc_compact |> 
  select(pnewsubcategory, colors) |> 
  distinct() |> 
  deframe()

# 5. Define Splits and Colors
row_split_compact <- factor(evardesc_compact$enewsubcategory)
row_split_compact <- fct_reorder(row_split_compact, evardesc_compact$super_ecat_number)

col_split_compact <- factor(pvardesc_compact$pnewsubcategory)
col_split_compact <- fct_reorder(col_split_compact, pvardesc_compact$pnewcat_order)

col_fun <- colorRamp2(c(-0.1, 0, 0.1), c("#2166AC", "white", "#B2182B"))

# 6. Build Annotations
rowAn_compact <- rowAnnotation(
  sc = evardesc_compact$enewsubcategory,
  show_legend = FALSE,
  show_annotation_name = FALSE,
  col = list(sc = envec_compact),
  width = unit(2, "mm")
)

colAn_compact <- columnAnnotation(
  sc = pvardesc_compact$pnewsubcategory,
  show_legend = FALSE,
  show_annotation_name = FALSE,
  col = list(sc = pnvec_compact),
  height = unit(2, "mm")
)

# 7. Create Heatmap
hm_compact <- Heatmap(
  to_array_pe_matrix,
  col = col_fun,
  left_annotation = rowAn_compact,
  top_annotation = colAn_compact,
  row_split = row_split_compact,
  column_split = col_split_compact,
  row_title_gp = gpar(fontsize = 5),
  row_title_rot = 0,
  column_title_gp = gpar(fontsize = 5),
  column_title_rot = 90,
  row_gap = unit(0.5, "mm"),
  column_gap = unit(0.5, "mm"),
  show_row_names = FALSE,
  show_column_names = FALSE,
  cluster_columns = FALSE,
  cluster_rows = FALSE,
  name = "Association",
  heatmap_legend_param = list(
    title_gp = gpar(fontsize = 5, fontface = "bold"),
    labels_gp = gpar(fontsize = 4),
    legend_height = unit(15, "mm")
  ),
  border = FALSE,
  rect_gp = gpar(col = NA)
)

# 8. Save and Draw
pdf(file = "./paper_figures_tables/atlas_fig_research_summary.pdf", width = width_in, height = height_in)
draw(hm_compact, padding = unit(c(2, 2, 2, 2), "mm"), heatmap_legend_side = "right")
dev.off()

suppressMessages(draw(hm_compact, padding = unit(c(2, 2, 2, 2), "mm"), heatmap_legend_side = "right"))
```
 
 
 
 
 
 


EE Architecture

```{r ee architecture correlation, fig.height=7, fig.width=7}
to_array <- adjusted_meta_to_hm |> filter(term_name == 'expo' | term_name == 'expo1') |> select(evarname, pvarname, estimate_overall, p.value_overall) |> mutate(estimate_overall= ifelse(p.value_overall >= 0.1, 0, estimate_overall)) |> mutate(estimate_overall = ifelse(is.na(estimate_overall), 0, estimate_overall))  |> select(-p.value_overall) |> pivot_wider(names_from = evarname, values_from = estimate_overall)

vardesc <- adjusted_meta_to_hm |> filter(term_name == 'expo' | term_name == 'expo1') |> select(evarname, ecategory, esubcategory) |> unique() |> as.data.frame()
rownames(vardesc) <- vardesc$evarname
vardesc <- vardesc |> select(-evarname)
ha <- rowAnnotation(sc=evardesc$enewsubcategory, show_legend=FALSE, show_annotation_name = FALSE, col=list(sc=envec))
hc <- columnAnnotation(sc=evardesc$enewsubcategory, show_legend=FALSE, show_annotation_name = FALSE, col=list(sc=envec))
phenome_correlation <- to_array |> select(-pvarname) |> correlate(diagonal = 1)
m <- phenome_correlation |> as_matrix()
m[is.na(m)] <- 0
Heatmap(m, right_annotation = ha, row_split = row_split_by_ecategory,
        bottom_annotation = hc, column_split = row_split_by_ecategory,
        row_title_gp    = gpar(fontsize = 8),   # shrink/enlarge row-split label text
        row_title_rot   = 0,  
        column_title_gp = gpar(fontsize = 8),   # shrink/enlarge column-split label text
        column_title_rot= 45,  
        show_row_names=F, show_column_names = F, cluster_rows = T, cluster_columns = T, show_column_dend = F, show_row_dend = F,
        name="Correlation")



ee_m <- m
```

```{r}

phenome_correlation_str <- phenome_correlation |> stretch() |> 
  right_join(
    adjusted_meta_to_hm |> select(evarname, enewsubcategory, evardesc) |> unique(), by=c("x"="evarname")) |> 
  right_join(
    adjusted_meta_to_hm |> select(evarname, enewsubcategory, evardesc) |> unique(), by=c("y"="evarname")
    ) 
  

phenome_correlation_str |> group_by(enewsubcategory.x, enewsubcategory.y) |> summarize(m=median(r, na.rm=T),m_abs=median(abs(r), na.rm=T), q25_abs=quantile(abs(r), probs=.25, na.rm=T),q75_abs=quantile(abs(r), probs=.75, na.rm=T)) 

phenome_correlation_str |> group_by(enewsubcategory.x) |> summarize(m=median(r, na.rm=T),m_abs=median(abs(r), na.rm=T), q25_abs=quantile(abs(r), probs=.25, na.rm=T),q75_abs=quantile(abs(r), probs=.75, na.rm=T)) 

phenome_correlation_str |> summarize(m=median(abs(r), na.rm=T))
phenome_correlation_str |> filter(x!=y) |> arrange(r) |> head(200) 

phenome_correlation_str |> filter(x=="LBXBCD", y=="URXUCD")
phenome_correlation_str |> filter(x=="LBXCOT", y=="URXCOTT")
phenome_correlation_str |> filter(x=="LBXBPB", y=="URXUPB")




```


PP Architecture
```{r pp architecture correlation, fig.height=7, fig.width=7}
to_array <- adjusted_meta_to_hm |> filter(term_name == 'expo' | term_name == 'expo1') |> select(evarname, pvarname, estimate_overall, p.value_overall) |> mutate(estimate_overall= ifelse(p.value_overall >= 0.1, 0, estimate_overall)) |> mutate(estimate_overall = ifelse(is.na(estimate_overall), 0, estimate_overall))  |> select(-p.value_overall) |> pivot_wider(names_from = pvarname, values_from = estimate_overall)

vardesc <- adjusted_meta_to_hm |> filter(term_name == 'expo' | term_name == 'expo1') |> select(pvarname, pcategory, pnewsubcategory) |> unique() |> as.data.frame()
rownames(vardesc) <- vardesc$pvarname
vardesc <- vardesc |> select(-pvarname)
ha <- rowAnnotation(sc=vardesc$pnewsubcategory, show_legend=FALSE, show_annotation_name = FALSE, col=list(sc=pnvec))
hc <- columnAnnotation(sc=vardesc$pnewsubcategory, show_legend=FALSE, show_annotation_name = FALSE, col=list(sc=pnvec))
phenome_correlation <- to_array |> select(-evarname) |> correlate(diagonal = 1)
m <- phenome_correlation |> as_matrix()
m[is.na(m)] <- 0
Heatmap(m, right_annotation = ha, row_split = col_split_by_pcategory,
        bottom_annotation = hc, column_split = col_split_by_pcategory,
        row_title_gp    = gpar(fontsize = 8),   # shrink/enlarge row-split label text
        row_title_rot   = 0,  
        column_title_gp = gpar(fontsize = 8),   # shrink/enlarge column-split label text
        column_title_rot= 45,  
        show_row_names=F, show_column_names = F, cluster_rows = T, cluster_columns = T, show_column_dend = F, show_row_dend = F,
        name="Correlation")

pp_m <- m
phenome_correlation_str <- phenome_correlation |> stretch() |> right_join(adjusted_meta_to_hm |> select(pvarname, pnewsubcategory, pvardesc) |> unique(), by=c("x"="pvarname"))

phenome_correlation_str |> group_by(pnewsubcategory) |> summarize(m=median(r, na.rm=T),m_abs=median(abs(r), na.rm=T), q25_abs=quantile(abs(r), probs=.25, na.rm=T),q75_abs=quantile(abs(r), probs=.75, na.rm=T)) 

phenome_correlation_str |> summarize(m=median(abs(r), na.rm=T))
phenome_correlation_str |> filter(x!=y) |> filter(x=='LBXGLU')|> arrange(r) |> head(200) 

```


Extended Data Figure 7 Source Data
```{r}
pp_m |> write.csv(file="ExtData7_PanelB.csv")
ee_m |> write.csv(file="ExtData7_PanelA.csv")
```
