---
title: "Consistency of Associations"
author: "Chirag Patel"
date: "`r Sys.Date()`"
output: html_document
---

# Internal consistency
## Comparing diet, biomarkers, and self reported measures


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r start anew}
if(exists("con")) {
  dbDisconnect(con)
}
remove(list=ls())
```

```{r}
library(tidyverse)
library(DBI)
library(ggsci)
library(DT)
library(ggrepel)
library(cowplot)


```

```{r combine within survey and glanced stats}
ep_assoc_summary_across_models <- function(summary_stats, glanced_stats) {
  summary_stats_wide <- summary_stats |> pivot_wider(names_from = "model_type", values_from = c("estimate", "std.error", "statistic", "p.value")) 
  summary_stats_wide <- summary_stats_wide |> mutate(estimate_diff = estimate_adjusted-estimate_unadjusted)
  adj_vs_base <- glanced |> select(-c(adj.r2, df.residual, null.deviance, df.null, deviance)) |> pivot_wider(names_from=model_type, values_from = c("rsq", "nobs", "AIC", "BIC"))
  adj_vs_base <- adj_vs_base |> mutate(rsq_adjusted_base_diff=rsq_adjusted-rsq_base, rsq_adjusted_diff = rsq_adjusted-rsq_unadjusted)
  summary_stats_wide |> left_join(adj_vs_base, by=c("evarname", "pvarname", "exposure_table_name", "phenotype_table_name"))
}
```

```{r connect to db}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats.sqlite')
varnames <- tbl(con, "variable_names_epcf")
adjusted_meta <- tbl(con, "adjusted_meta")
unadjusted_meta <- tbl(con, "unadjusted_meta")
adjusted_meta <- adjusted_meta |> left_join(unadjusted_meta |> select(evarname, pvarname, expo_name, vartype, estimate, p.value) |> rename(estimate_unadjusted=estimate, p.value_unadjusted=p.value), by=c("evarname", "pvarname", "expo_name", "vartype"))
mvr2 <- tbl(con, 'mvr2') |> mutate(mv = mve_rsq-base_rsq)
pe <- tbl(con, "pe")
glanced <- tbl(con, "glanced")
variable_domain <- tbl(con, "variable_domain")
adjusted_meta_2 <- tbl(con, "adjusted_meta_2") |> rename(evardesc = pvardesc.y)
```


## Day 1 vs. Day 2 Self-Report Estimates
```{r, DS1 v DS2}
ds1 <- adjusted_meta_2 |> collect() |> filter(grepl("^DS1", evarname))
ds2 <- adjusted_meta_2 |> collect() |> filter(grepl("^DS2", evarname))
ds1 <- ds1 |> mutate(evarnameds=substr(evarname, 4, 20))
ds2 <- ds2 |> mutate(evarnameds=substr(evarname, 4, 20))

## now merge the 2
ds <- ds1 |> left_join(ds2, by=c("evarnameds", "pvarname"), suffix=c("_DS1", "_DS2"))
## plot a scatter of the estimates
p <- ggplot(ds, aes(estimate_DS1, estimate_DS2, color=sig_levels_DS1))
p <- p + geom_point()
p <- p + geom_abline() + geom_hline(yintercept=0) + geom_vline(xintercept =0)
p <- p + xlab("Effect Size Estimate (Day 1)")
p <- p + ylab("Effect Size Estimate (Day 2)") + facet_grid(~sig_levels_DS1) +scale_color_aaas()
p <- p  +  theme_bw() + theme(legend.title=element_blank()) 
p

ds |> group_by(sig_levels_DS1) |> summarize(cr = cor(estimate_DS1, estimate_DS2, use="pairwise.complete.obs"))

```


## Urine vs. Blood

```{r}

lbx_vars <- adjusted_meta_2 |> collect() |> filter(grepl("^LBX", evarname)) |> select(evarname, evardesc) |> unique()
urx_vars <- adjusted_meta_2 |> collect() |> filter(grepl("^URX", evarname)) |> select(evarname, evardesc) |> unique()


# mapping:
lbx_urx_mapping <- tibble(urx_evarname=c("URXUHG", "URXUCD", "URXBPB", "URXCOTT"), 
                      lbx_evarname=c("LBXTHG", "LBXBCD", "LBXBPB", "LBXCOT"), 
                      urx_lbx_name = c('HG', 'CD', 'PB', 'COT'))

lbx_dat <- adjusted_meta_2 |> collect() |> right_join(lbx_urx_mapping, by=c("evarname"="lbx_evarname"))
urx_dat <- adjusted_meta_2 |> collect() |> right_join(lbx_urx_mapping, by=c("evarname"="urx_evarname"))

lbx_urx <- lbx_dat |> inner_join(urx_dat, by=c("urx_lbx_name", "pvarname"), suffix=c("_lbx", "_urx"))

p <- ggplot(lbx_urx, aes(estimate_lbx, estimate_urx, color=sig_levels_lbx))
p <- p + geom_point() 
p <- p + geom_abline() + geom_hline(yintercept=0) + geom_vline(xintercept =0) + facet_grid(urx_lbx_name~sig_levels_lbx) +scale_color_aaas()
p <- p +  theme_bw() + theme(legend.title=element_blank()) + xlab("Effect Size Estimate of Blood Biomarker") + ylab("Effect Size Estimate of Urinary Biomarker")



lbx_urx |> group_by(urx_lbx_name, sig_levels_lbx) |> summarize(cr=cor(estimate_lbx, estimate_urx))

```


Self-report vs. biomarker

```{r}
lbx_sr_mapping <- tibble(sr_evarname=c("DR1TVB12", "DR1TBCAR", "DR1TBCAR", "DR1TACAR", "DR1TCRYP", "DR1TRET", "DR1TVD"), 
                      lbx_evarname=c("LBXB12", "LBXBEC","LBXCBC", "LBXALC", "LBXCRY", "LBXVIA", "LBXVIDMS"),
                      lbx_sr_name = c('B12', 'TBCAR', 'CBCAR', "ACAR", "CRYP", "RET", "VD")) 

sr_dat <- adjusted_meta_2 |> collect() |> right_join(lbx_sr_mapping, by=c("evarname"="sr_evarname"))
lbx2_dat <- adjusted_meta_2 |> collect() |> right_join(lbx_sr_mapping, by=c("evarname"="lbx_evarname"))
lbx_sr <- lbx2_dat |> inner_join(sr_dat, by=c("lbx_sr_name", "pvarname"), suffix=c("_lbx", "_sr"))

p <- ggplot(lbx_sr, aes(estimate_lbx, estimate_sr, color=sig_levels_lbx))
p <- p + geom_point() 
p <- p + geom_abline() + geom_hline(yintercept=0) + geom_vline(xintercept =0) + facet_grid(lbx_sr_name~sig_levels_lbx) +scale_color_aaas()
p <- p +  theme_bw() + theme(legend.title=element_blank())  + xlab("Effect Size Estimate of Blood Biomarker") + ylab("Effect Size Estimate of Self-Report Exposure")
p


lbx_sr |> group_by(sig_levels_lbx) |> summarize(cr=cor(estimate_lbx,estimate_sr))

```
