---
title: "ExE"
author: "Chirag Patel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(DBI)
library(ggsci)
library(DT)
library(ggrepel)
library(cowplot)
library(reactable)
library(gt)
library(broom)
library(igraph)
library(gplots)
```



```{r connect to db}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/ee_summary_stats_03_2024.sqlite')
varnames <- tbl(con, "variable_names_epcf")
adjusted_meta <- tbl(con, "adjusted_meta")
pe <- tbl(con, "pe")
pe_r2 <- tbl(con, "rsq")
glanced <- tbl(con, "glanced")
glanced <- glanced |> left_join(pe_r2 |> select(xvar, yvar, series, model_number,aggregate_base_model, rsq, adj.r2), by=c("xvar", "yvar", "model_number", "aggregate_base_model", "series"))
variable_domain <- tbl(con, "variable_domain")
```

```{r}
expos <- pe |> filter(term %like% 'expo%') |> rename(xvarname=xvar, yvarname=yvar)
expos_wide <- expos |> pivot_wider(names_from = "model_number", values_from = c("estimate", "std.error", "statistic", "p.value")) 
glanced_wide <- glanced |> select(-c(adj.r2, df.residual, null.deviance, df.null, deviance)) |> pivot_wider(names_from=c("model_number", "aggregate_base_model"), values_from = c("rsq", "nobs", "AIC", "BIC")) |>  rename(xvarname=xvar, yvarname=yvar)

glanced_wide <- glanced_wide |> mutate(rsq_adjusted_base_diff=rsq_2_0-rsq_2_1, rsq_adjusted_diff = rsq_2_0-rsq_1_0) 

expos_wide <- expos_wide |> left_join(glanced_wide |> select(-c(series, log_y, log_x, scaled_y, scaled_x)), by=c("xvarname", "yvarname", "x_table_name", "y_table_name"))
expos_wide <- expos_wide |> left_join(varnames, by=c("xvarname"="Variable.Name", "x_table_name"="Data.File.Name"))
expos_wide <- expos_wide |> left_join(varnames |> select(Variable.Name, Data.File.Name, Variable.Description, Data.File.Description), by=c("yvarname"="Variable.Name", "y_table_name"="Data.File.Name"))


expos_wide <- expos_wide |> collect() |> select(-Use.Constraints) |> rename(x_data_file_desc=Data.File.Description.x, y_data_file_desc=Data.File.Description.y,x_variable_description=Variable.Description.x, y_variable_description=Variable.Description.y)

expos_wide_summary <- expos_wide |> filter(term == 'expo' | term == 'expo1' | term == 'expo2') |> group_by(xvarname, yvarname) |> summarize(mean_adjusted_base_r2_diff = mean(rsq_adjusted_base_diff), mean_unadjusted_r2_diff=mean(rsq_adjusted_diff), total_n = sum(nobs_2_0)) |> ungroup()

adjusted_meta_full <- adjusted_meta |> filter(model_number == 2) |> collect() |> left_join(expos_wide_summary, by=c("xvarname", "yvarname")) ## fully adjusted model
adjusted_meta_raw <- adjusted_meta |> filter(model_number == 1) |> collect() |> left_join(expos_wide_summary, by=c("xvarname", "yvarname"))  |> select(-error)

y_variable_domain <- variable_domain |> filter(epcf == 'e') |> collect() |> group_by(Variable.Name) |> summarise(yvardesc=first(Variable.Description),ycategory=first(category),ysubcategory=first(subcategory))
x_variable_domain <- variable_domain |> filter(epcf == 'e') |> collect() |> group_by(Variable.Name) |> summarise(xvardesc=first(Variable.Description),xcategory=first(category),xsubcategory=first(subcategory))

adjusted_meta_full <- adjusted_meta_full |> left_join(y_variable_domain, by=c("yvarname"="Variable.Name"))
adjusted_meta_full <- adjusted_meta_full |> left_join(x_variable_domain, by=c("xvarname"="Variable.Name"))

adjusted_meta_raw <- adjusted_meta_raw |> left_join(y_variable_domain, by=c("yvarname"="Variable.Name"))
adjusted_meta_raw <- adjusted_meta_raw |> left_join(x_variable_domain, by=c("xvarname"="Variable.Name"))


expos_wide <- expos_wide |> left_join(y_variable_domain, by=c("yvarname"="Variable.Name"))
expos_wide <- expos_wide |> left_join(x_variable_domain, by=c("xvarname"="Variable.Name"))
```



```{r}
adjusted_meta_raw_2 <- adjusted_meta_raw |> filter(nobs > 1)
quantile(abs(adjusted_meta_raw_2$estimate), probs=c(0, .05, .25, .5, .75, .8, .9, .95, .99))
ecdf(abs(adjusted_meta_raw_2$estimate))(.99)
adjusted_meta_raw_2 <- adjusted_meta_raw_2 |> mutate(pval.bonf = p.adjust(p.value))
sig <- adjusted_meta_raw_2 |> filter(p.value < 0.0001)
quantile(abs(sig$estimate), probs=c(0, .05, .25, .5, .75, .8, .9, .95, .99))


p <- ggplot(adjusted_meta_raw_2 |> filter(abs(estimate) <= 1), aes(estimate, color=factor(pval.bonf < 0.05)))
p <- p + stat_ecdf() 
p

p <- ggplot(sig |> filter(abs(estimate) <= 1), aes(estimate))
p <- p + geom_histogram()
p

## try dividing by category
p <- ggplot(sig |> filter(abs(estimate) <= 1), aes(estimate, color=xcategory))
p <- p + geom_histogram()
p

p <- ggplot(sig |> filter(abs(estimate) <= 1), aes(xcategory, estimate, color=xcategory))
p <- p + geom_boxplot() + facet_grid(~ycategory) + scale_color_jama()
p


```

## Heatmaps
```{r}
heatmapColors <- function(numColors=8) {
	c1 <- rainbow(numColors,v=seq(0.5,1,length=numColors),s=seq(1,0.3,length=numColors),start=4/6,end=4.0001/6);
	c2 <- rainbow(numColors,v=seq(0.5,1,length=numColors),s=seq(1,0.3,length=numColors),start=1/6,end=1.0001/6);
	c3 <- c(c1,rev(c2)); 
	return(c3)
}

## go wide 
data_non_redundant <- sig |> filter(abs(estimate) <= 1) |> select(estimate, xvarname, yvarname) |>
  mutate(pair = pmap_chr(list(xvarname, yvarname), ~paste(sort(c(...)), collapse = "-"))) %>%
  distinct(pair, .keep_all = TRUE) %>%
  separate(pair, into = c("xvar_new", "yvar_new"), sep = "-") %>%
  select(-xvarname, -yvarname) %>%
  rename(xvarname = xvar_new, yvarname = yvar_new)

# Create the correlation matrix
create_corr_matrix_from_df <- function(data_non_redundant) {
  # xvarname, yvarname, estimate
  all_vars <- sort(unique(c(data_non_redundant$xvarname, data_non_redundant$yvarname)))
  n_vars <- length(all_vars)
  cor_matrix <- matrix(NA, nrow = n_vars, ncol = n_vars, dimnames = list(all_vars, all_vars))
  for (i in 1:nrow(data_non_redundant)) {
    row <- data_non_redundant[i, ]
    x_pos <- match(row$xvarname, all_vars)
    y_pos <- match(row$yvarname, all_vars)
  
    cor_matrix[x_pos, y_pos] <- row$estimate
    cor_matrix[y_pos, x_pos] <- row$estimate  # Ensure symmetry
  }
  cor_matrix
}

cor_matr <- create_corr_matrix_from_df(data_non_redundant)

## color by category the side colors
xcategories_per_var <- sig |> group_by(xvarname, xcategory, xsubcategory) |> count()
ycategories_per_var <- sig |> group_by(yvarname, ycategory, ysubcategory) |> count()
categories_per_var <- rbind( ycategories_per_var |> rename(varname=yvarname, category=ycategory,subcategory=ysubcategory),
                             xcategories_per_var |> rename(varname=xvarname, category=xcategory, subcategory=xsubcategory)
) |> select(-n) |> unique()


color_palette <- brewer.pal(n = length(unique(categories_per_var$category)), name = "Paired")
category_colors <- tibble(category=unique(categories_per_var$category), col=color_palette)
categories_per_var <- categories_per_var |> left_join(category_colors, by="category")
category_colors_cor <- tibble(varname=rownames(cor_matr), 
                              col_num=1:length(rownames(cor_matr))) |> left_join(categories_per_var, by="varname")

category_colors_cor <- category_colors_cor |> mutate(lab=paste(category, subcategory))
  
## sort the order of the cor_matr in the order of the categories
cor1 <- cor_matr[category_colors_cor |> arrange(category) |> pull(varname), category_colors_cor |> arrange(category) |> pull(varname)]
category_colors_cor <- category_colors_cor |> arrange(category)
heatmap.2(cor1, Rowv=F, Colv=F, dendrogram="none", trace="none", 
          rowsep = 0, colsep = 0, labRow=category_colors_cor$lab, labCol=category_colors_cor$lab,
          col=heatmapColors(8), 
          ColSideColors = category_colors_cor$col, RowSideColors = category_colors_cor$col)

## try filtering on categories - it works
cor2 <- cor_matr[category_colors_cor |> filter(category=='nutrients') |> pull(varname), category_colors_cor |> filter(category=='nutrients') |> pull(varname)]
category_colors_cor2 <- category_colors_cor |> filter(category == 'nutrients')
heatmap.2(cor2, Rowv=F, Colv=F, dendrogram="none", trace="none", 
          rowsep = 0, colsep = 0, labRow=category_colors_cor2$lab, labCol=category_colors_cor2$lab,
          col=heatmapColors(8), 
          ColSideColors = category_colors_cor2$col, RowSideColors = category_colors_cor2$col)

## try filtering on pollutants
cor3 <- cor_matr[category_colors_cor |> filter(category=='pollutant' | category == 'smoking') |> pull(varname), category_colors_cor |> filter(category=='pollutant' | category == 'smoking') |> pull(varname)]
category_colors_cor3 <- category_colors_cor |> filter(category=='pollutant' | category == 'smoking')
heatmap.2(cor3, Rowv=F, Colv=F, dendrogram="none", trace="none", 
          rowsep = 0, colsep = 0, labRow=category_colors_cor3$lab, labCol=category_colors_cor3$lab,
          col=heatmapColors(8), 
          ColSideColors = category_colors_cor3$col, RowSideColors = category_colors_cor3$col)
```


# adjusted vs. non-adjusted

```{r}
raw_sig <- adjusted_meta_raw |> filter(nobs > 1) |> filter(p.value < 0.0001, abs(estimate) <= 1)
adj_sig <- adjusted_meta_full |> filter(nobs > 1) 

raw_adj <- raw_sig |> left_join(adj_sig |> select(term_name, xvarname, yvarname, estimate), by=c("term_name", "xvarname", "yvarname"))

p <- ggplot(raw_adj, aes(estimate.x-estimate.y))
p <- p  +geom_histogram() + scale_x_continuous(limits=c(-1, 1))
p

p <- ggplot(raw_adj, aes(estimate.x,estimate.y))
p <- p  +geom_point(shape=".") + scale_x_continuous(limits=c(-1, 1)) + scale_y_continuous(limits=c(-1, 1))
p

glance(lm(estimate.y ~ estimate.x, raw_adj))

```

```{r}
sig_graph <- sig |> select(-term_name) |> select(xvarname, yvarname, everything()) 
sig_vertex <- sig_graph |> select(xvarname, xcategory) |> unique() |> rename(varname = xvarname, category=xcategory)
sig_vertex2 <- sig_graph |> select(yvarname, ycategory) |> unique() |> rename(varname = yvarname, category=ycategory)
sig_vertex <- sig_vertex |> rbind(sig_vertex2) |> unique()

g <- graph_from_data_frame(sig_graph, directed = FALSE) # Use directed = TRUE if your graph is directed
V(g)$category <- sig_vertex$category[match(V(g)$name, sig_vertex$varname)]
categories <- unique(V(g)$category)
# Assign colors to each category
category_colors <- setNames(rainbow(length(categories)), categories)
# Map the colors to vertices based on category
vertex_colors <- category_colors[V(g)$category]

coords <- layout_in_circle(g)

plot(g, 
     vertex.color = vertex_colors, vertex.size = 1,
     edge.width = abs(E(g)$estimate), layout=coords, vertex.label=NA)

```






