---
title: "Effect Sizes"
author: "Chirag Patel"
date: "`r Sys.Date()`"
output: html_document
---


This new .Rmd incorporates the effect sizes comparing the top 10% vs. 1SD of exposure, and also has a new Manhattan Plot procedure.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(DBI)
library(ggsci)
library(DT)
library(ggrepel)
library(cowplot)
library(reactable)
library(gt)
library(broom)
library(ggridges)
```



```{r connect to db of summary stats}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_08_2024.sqlite')
varnames <- tbl(con, "variable_names_epcf")
adjusted_meta <- tbl(con, "adjusted_meta_uwls") |> rename(term_name=expo_name)
mvr2 <- read_rds('../pe_summary_060623/mvr2.rds') |> mutate(mv = mve_rsq-base_rsq)
pe <- tbl(con, "pe") ## individual surveys
pe_r2 <- tbl(con, "rsq")
glanced <- tbl(con, "glanced")
glanced <- glanced |> left_join(pe_r2 |> select(exposure, phenotype, series, model_number,aggregate_base_model, rsq, adj.r2), by=c("exposure", "phenotype", "model_number", "aggregate_base_model", "series"))
variable_domain <- tbl(con, "variable_domain")
pe_overall <- tbl(con, "pe_overall")
r2_overall <- tbl(con, "rsq_overall")
glanced_overall <- tbl(con, "glanced_overall")
glanced_overall <- glanced_overall |> left_join(r2_overall |> select(exposure, phenotype, model_number,aggregate_base_model, rsq, adj.r2), by=c("exposure", "phenotype", "model_number", "aggregate_base_model"))

```

```{r}
expos <- pe |> filter(term %like% 'expo%') |> rename(evarname=exposure, pvarname=phenotype)
expos_wide <- expos |> pivot_wider(names_from = "model_number", values_from = c("estimate", "std.error", "statistic", "p.value")) 
glanced_wide <- glanced |> select(-c(adj.r2, df.residual, null.deviance, df.null, deviance)) |> pivot_wider(names_from=c("model_number", "aggregate_base_model"), values_from = c("rsq", "nobs", "AIC", "BIC")) |>  rename(evarname=exposure, pvarname=phenotype)
glanced_wide <- glanced_wide |> mutate(rsq_adjusted_base_diff=rsq_2_0-rsq_2_1, rsq_adjusted_diff = rsq_2_0-rsq_1_0) 
glanced_overall_wide <- glanced_overall |> select(-c(adj.r2, df.residual, null.deviance, df.null, deviance)) |> pivot_wider(names_from=c("model_number", "aggregate_base_model"), values_from = c("rsq", "nobs", "AIC", "BIC")) |>  rename(evarname=exposure, pvarname=phenotype)

expos_wide <- expos_wide |> left_join(glanced_wide |> select(-c(series, log_p, log_e, scaled_p, scaled_e)), by=c("evarname", "pvarname", "exposure_table_name", "phenotype_table_name"))
expos_wide <- expos_wide |> left_join(varnames, by=c("evarname"="Variable.Name", "exposure_table_name"="Data.File.Name"))
expos_wide <- expos_wide |> left_join(varnames |> select(Variable.Name, Data.File.Name, Variable.Description, Data.File.Description), 
                                      by=c("pvarname"="Variable.Name", "phenotype_table_name"="Data.File.Name"))

expos_wide <- expos_wide |> collect() |> select(-Use.Constraints) |> rename(e_data_file_desc=Data.File.Description.x, p_data_file_desc=Data.File.Description.y,e_variable_description=Variable.Description.x, p_variable_description=Variable.Description.y)

#expos_wide_summary <- expos_wide |> filter(term == 'expo' | term == 'expo1' | term == 'expo2') |> group_by(evarname, pvarname) |> summarize(mean_adjusted_base_r2_diff = mean(rsq_adjusted_base_diff), mean_unadjusted_r2_diff=mean(rsq_adjusted_diff), total_n = sum(nobs_2_0)) |> ungroup()

glanced_summary <- glanced_overall_wide |> mutate(total_n = nobs_2_0, rsq_adjusted_base_diff = rsq_2_0-rsq_2_1, rsq_adjusted_diff=rsq_2_0-rsq_1_0) |> 
  select(evarname, pvarname, rsq_adjusted_base_diff, rsq_adjusted_diff, total_n)

adjusted_meta_full <- adjusted_meta |> filter(model_number == 2)  |> left_join(glanced_summary, by=c("evarname", "pvarname")) |> collect() ## fully adjusted model

p_variable_domain <- variable_domain |> filter(epcf == 'p') |> collect() |> group_by(Variable.Name) |> summarise(pvardesc=first(Variable.Description),pcategory=first(category),psubcategory=first(subcategory))
e_variable_domain <- variable_domain |> filter(epcf == 'e') |> collect() |> group_by(Variable.Name) |> summarise(evardesc=first(Variable.Description),ecategory=first(category),esubcategory=first(subcategory))

adjusted_meta_full <- adjusted_meta_full |> left_join(p_variable_domain, by=c("pvarname"="Variable.Name"))
adjusted_meta_full <- adjusted_meta_full |> left_join(e_variable_domain, by=c("evarname"="Variable.Name"))
expos_wide <- expos_wide |> left_join(p_variable_domain, by=c("pvarname"="Variable.Name"))
expos_wide <- expos_wide |> left_join(e_variable_domain, by=c("evarname"="Variable.Name"))
mvr2 <- mvr2 |> collect() |> left_join(p_variable_domain, by=c("pvarname"="Variable.Name"))

pe_overall_full <- pe_overall |> filter(model_number == 2, term %like% "expo%") |> select(term, estimate, std.error, statistic, p.value, exposure, phenotype) |> 
  rename(evarname = exposure, pvarname = phenotype, term_name=term) |> collect()

adjusted_meta_full <- adjusted_meta_full |> left_join(pe_overall_full, by=c("term_name", "evarname", "pvarname"), suffix=c("", "_overall"))

adjusted_meta_full <- adjusted_meta_full |> mutate(estimate_overall=ifelse(k.uwls == 1, estimate.uwls, estimate), 
                                                   p.value_overall=ifelse(k.uwls == 1, p.value.uwls, p.value),
                                                   std.error_overall=ifelse(k.uwls == 1, std.error.uwls, std.error), 
                                                   statistic_overall=ifelse(k.uwls == 1, statistic.uwls, statistic)
                                                   )
```

```{r filter exposure categories}
exposure_categories <- c("pollutant", "nutrients", "smoking", "infection")
adjusted_meta_full <- adjusted_meta_full |> filter(ecategory %in% exposure_categories)
expos_wide <- expos_wide |> filter(ecategory %in% exposure_categories)

```


```{r}
adjusted_meta_full <- adjusted_meta_full |> mutate(nobs = k.uwls)
n_obss <- sort(unique(adjusted_meta_full$nobs))

num_tests <- map_df(n_obss, function(n) {
  n_e <- adjusted_meta_full |> filter(nobs >= n) |> pull(evarname) |> unique() |> length()
  n_p <- adjusted_meta_full |> filter(nobs >= n) |> pull(pvarname) |> unique() |> length()
  nn <- nrow(adjusted_meta_full |> filter(nobs == n))
  tibble(n_expos=n_e, n_phenos=n_p, n_pxe=nn)
})

num_tests  |> mutate(n_surveys=n_obss) |> gt()



```

```{r}
# Keep number of surveys is greater than 2
adjusted_meta_2 <- adjusted_meta_full |> filter(nobs >= 2)
n_evars <- length(unique(adjusted_meta_2$evarname))
n_pvars <- length(unique(adjusted_meta_2$pvarname))
n_evars
n_pvars
```

Sample sizes within and across all surveys
```{r sample sizes}
sample_size_per_pair <- expos_wide |> filter(term == 'expo' | term== 'expo1') |> group_by(evarname, pvarname) |> summarize(total_n=sum(nobs_2_0), n_surveys=n(), median_n=median(nobs_2_0))

```

```{r}
adjusted_meta_2 <- adjusted_meta_2 |> filter(!is.na(estimate_overall), !is.na(p.value_overall))
adjusted_meta_2 <- adjusted_meta_2 |> ungroup() |>  mutate(pval_BY=p.adjust(p.value_overall, method="BY"), pvalue_bonferroni=p.adjust(p.value_overall, method="bonferroni"))
adjusted_meta_2 <- adjusted_meta_2 |> mutate(sig_levels = case_when(
  pvalue_bonferroni < 0.05 ~ 'Bonf.<0.05',
  pval_BY < 0.05 ~ 'BY<0.05',
  TRUE ~ '> BY & Bonf.'
))
```



```{r rename subcategories}

adjusted_meta_2 <- adjusted_meta_2 |> mutate(
  pnewsubcategory =  case_when(
    psubcategory == 'injury' ~ "inflammation",
    psubcategory == 'liver/kidney' ~ "kidney",
    psubcategory == 'immunity' ~ "liver",
    psubcategory == 'exhaled NO' ~ "inflammation",
    psubcategory == 'lung function' ~ "lung",
    psubcategory == 'nutritional status' ~ "nutrition",
    TRUE ~ psubcategory
  )
)

adjusted_meta_2 <- adjusted_meta_2 |> mutate(pnewsubcategory = ifelse(is.na(pnewsubcategory), pcategory, pnewsubcategory))
adjusted_meta_2 <- adjusted_meta_2 |> mutate(enewsubcategory = ifelse(ecategory == 'infection', 'infection', esubcategory))
adjusted_meta_2 <- adjusted_meta_2 |> mutate(enewsubcategory = ifelse(enewsubcategory == 'pyrethoid', 'pyrethroid', enewsubcategory)) 
adjusted_meta_2 <- adjusted_meta_2 |> mutate(enewsubcategory = ifelse(enewsubcategory == 'amine' | enewsubcategory == 'amide', 'amine/amide', enewsubcategory))
adjusted_meta_2 <- adjusted_meta_2 |> mutate(enewsubcategory = ifelse(enewsubcategory == 'deet', 'amine/amide', enewsubcategory))

```

```{r}
## phenotype-specific correction
adjusted_meta_2 <- adjusted_meta_2 |> group_by(pvarname) |> mutate(pval_BY_pheno=p.adjust(p.value_overall, method="BY")) |> ungroup()
```



```{r}
con_q  <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_percentile_10_2024.sqlite')
pe_overall_q <- tbl(con_q, "pe_overall")
pe_quantile <- pe_overall_q |> filter( model_number == 2) |> filter(term == 'expoq2' | term =='expoq3' | term == 'expoq4' | term=='expoq5') |> collect()
dbDisconnect(con_q)


pe_quantile <- pe_quantile |> rename(evarname=exposure, pvarname=phenotype)
pe_quantile <- pe_quantile |> mutate(exposure_level = case_when(
  term == 'expoq2' ~ 'Q[25-50)',
  term == 'expoq3' ~ 'Q[50-75)',
  term == 'expoq4' ~ 'Q[75-90)',
  term == 'expoq5' ~ 'Q[90-100)',
  TRUE ~ NA_character_
))


linear_res <- adjusted_meta_2 |> filter(term_name == 'expo') |> select(evarname, pvarname, estimate_overall, sig_levels, ecategory, esubcategory, pcategory, psubcategory, enewsubcategory, pnewsubcategory)

pe_quantile_all <- pe_quantile |> left_join(linear_res, by=c("evarname", "pvarname"))
pe_quantile_top <- pe_quantile_all |> filter(sig_levels == 'Bonf.<0.05')


p <- ggplot(pe_quantile_top, aes(y=exposure_level, x=I(abs(estimate))))
p <- p + geom_density_ridges()+ scale_x_continuous(limits=c(0, .7))
p <- p + xlab("Absolute value of Effect Size [1SD of Phenotype]") + ylab("Quantile of Exposure")
p

p <- ggplot(pe_quantile_top, aes(y=exposure_level, x=I(abs(estimate)), fill=ecategory))
p <- p + geom_density_ridges()+ scale_x_continuous(limits=c(0, .7)) + facet_grid(pnewsubcategory~enewsubcategory) + scale_fill_tron()
p <- p + xlab("Absolute value of Effect Size [1SD of Phenotype]") + ylab("Quantile of Exposure")
p <- p + theme_bw()
p

p <- ggplot(pe_quantile_top, aes(y=exposure_level, x=I(abs(estimate))))
p <- p + geom_density_ridges2(stat="binline", bins=20)+ scale_x_continuous(limits=c(0, .7)) + facet_grid(~pnewsubcategory) +scale_fill_tron()
p <- p + xlab("Absolute value of Effect Size [1SD of Phenotype]") + ylab("Quantile of Exposure")
p <- p + theme_bw() + theme()
p

p <- ggplot(pe_quantile_top, aes(x=exposure_level, y=I(abs(estimate)), fill=pnewsubcategory))
p <- p + geom_boxplot()+ scale_y_continuous(limits=c(0, .7))
p <- p + ylab("Effect Size [1SD of Phenotype]") + xlab("Quantile of Exposure")
p <- p + theme_bw() + theme()
p

```


```{r}

pe_quantile_top |> filter(term == "expoq5") |> group_by(esubcategory) |> 
  summarize(med_estimate = median(abs(estimate)),
            med_estimate = quantile(abs(estimate)),
            med_pvalue = median((p.value))
            )



```

Compare the pvalues from the two different approaches

```{r}

pval_compare <- pe_quantile |> filter(term == 'expoq5') |> select(evarname, pvarname, estimate, p.value) |> right_join(adjusted_meta_2, by=c("evarname", "pvarname"))

ggplot(pval_compare, aes(-log10(p.value.x), -log10(p.value_overall))) + geom_point()
```



```{r}
con_q_nat_scale <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_percentile_noscale_p_10_2024.sqlite')
pe_overall_q_nat_scale <- tbl(con_q_nat_scale, "pe_overall")
pe_overall_q_nat_2 <- pe_overall_q_nat_scale |> filter( model_number == 2)


pe_overall_q_nat_2 |> filter(exposure == 'LBXGTC', phenotype == "BMXBMI", aggregate_base_model == 0)
## 5 greater points in BMI )vs. the lowest exposure group

pe_overall_q_nat_2 |> filter(exposure == 'LBXBPB', phenotype == "BMXHT", aggregate_base_model == 0)
## -3cm lower height for


pe_overall_q_nat_2 |> filter(phenotype == 'BMXHT', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Height (cm)")

pe_overall_q_nat_2 |> filter(phenotype == 'LBXGH', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Hemoglobin A1C%")

pe_overall_q_nat_2 |> filter(phenotype == 'LBXGLU', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Fasting Glucose (mg/dL)")

pe_overall_q_nat_2 |> filter(phenotype == 'LBDLDL', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("LDL Cholesterol (mg/dL)")

pe_overall_q_nat_2 |> filter(phenotype == 'SPXNFEV1', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("FEV1")
pe_overall_q_nat_2 |> filter(phenotype == 'SPXNFEV1', aggregate_base_model==0, term == 'expoq5') |> arrange(statistic)


pe_overall_q_nat_2 |> filter(phenotype == 'LBXTC', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Total Cholesterol (mg/dL)") + theme_bw()


```
