---
title: "Effect Size Examples"
author: "Chirag Patel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(DBI)
library(ggsci)
library(DT)
library(ggrepel)
library(cowplot)
library(reactable)
library(gt)
library(broom)
library(ggridges)
```

```{r}
con_q_nat_scale <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_percentile_noscale_p_10_2024.sqlite')
con <-  DBI::dbConnect(RSQLite::SQLite(), dbname='../db/nhanes_012324.sqlite')
varnames <- tbl(con, "variable_names_epcf")
pe_overall_q_nat_scale <- tbl(con_q_nat_scale, "pe_overall")
pe_overall_q_nat_2 <- pe_overall_q_nat_scale |> filter( model_number == 2)
```

## choose the highest ones from each phenotype group in a blood panel, 3x3 plot
## BMI
## TC
## HA1C
## FEV
## CRP
## AST/ALT
## BP
## SCR
## Hemoglobin


```{r}
pe_overall_q_nat_2 |> filter(exposure == 'LBXGTC', phenotype == "BMXBMI", aggregate_base_model == 0)
## 5 greater points in BMI )vs. the lowest exposure group

pe_overall_q_nat_2 |> filter(exposure == 'LBXBPB', phenotype == "BMXHT", aggregate_base_model == 0)
## -3cm lower height for
```


```{r}
## annotate each with top and bottom effect sizes and names of exposures
pe_overall_q_nat_2 |> filter(phenotype == 'BMXHT', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Height (cm)") + theme_bw()

pe_overall_q_nat_2 |> filter(phenotype == 'LBXGH', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Hemoglobin A1C%") + theme_bw()

pe_overall_q_nat_2 |> filter(phenotype == 'LBXGLU', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Fasting Glucose (mg/dL)") + theme_bw()

pe_overall_q_nat_2 |> filter(phenotype == 'LBDLDL', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("LDL Cholesterol (mg/dL)") + theme_bw()

pe_overall_q_nat_2 |> filter(phenotype == 'SPXNFEV1', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("FEV1") + theme_bw()


pe_overall_q_nat_2 |> filter(phenotype == 'LBXTC', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Total Cholesterol (mg/dL)") + theme_bw()

pe_overall_q_nat_2 |> filter(phenotype == 'LBXSCR', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Serum Creatinine (mg/dL)") + theme_bw()

pe_overall_q_nat_2 |> filter(phenotype == 'LBXHGB', aggregate_base_model==0, term == 'expoq5') |> ggplot(aes(estimate)) + geom_histogram() + xlab("Hemoglobin (mg/dL)") + theme_bw()


```


Effect size per pheno: top 10%
```{r}

pheno_top_expo_hist <- function(phenotype_name, annot_with_expos=NULL) {
  pheno_dat <- pe_overall_q_nat_2 |> filter(phenotype == phenotype_name, aggregate_base_model==0, term == 'expoq5')
  desc <- varnames |> filter(Variable.Name == phenotype_name) |> pull(Variable.Description)
  pl <- ggplot(pheno_dat, aes(estimate)) + geom_histogram()
  pl <- pl+ xlab(desc) + ylab("Count of Associations")
  pl <- pl + theme_bw()
  list(pl=pl, pheno_dat = pheno_dat)
}

ll <- pheno_top_expo_hist("BMXHT") ## 

```