---
title: "Correlation Globes"
author: "Chirag Patel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(DBI)
library(igraph)
library(ggsci)
```

# Exposome Globes: visualizing the correlation between variables

```{r}
get_data <- function(dbname) {
  con <- DBI::dbConnect(RSQLite::SQLite(), dbname=dbname)
  varnames <- tbl(con, "variable_names_epcf")
  adjusted_meta <- tbl(con, "adjusted_meta")
  pe <- tbl(con, "pe")
  pe_r2 <- tbl(con, "rsq")
  glanced <- tbl(con, "glanced")
  glanced <- glanced |> left_join(pe_r2 |> select(xvar, yvar, series, model_number,aggregate_base_model, rsq, adj.r2), by=c("xvar", "yvar", "model_number", "aggregate_base_model", "series"))
  variable_domain <- tbl(con, "variable_domain")
  dbdata <- list(connection=con, varnames=varnames, adjusted_meta = adjusted_meta, pe=pe, pe_r2=pe_r2, glanced=glanced, variable_domain=variable_domain)
}

```

```{r}

process_data <- function(dbdata, e_or_p='p') {
  expos <- dbdata$pe |> filter(term %like% 'expo%') |> rename(xvarname=xvar, yvarname=yvar)
  expos_wide <- expos |> pivot_wider(names_from = "model_number", values_from = c("estimate", "std.error", "statistic", "p.value")) 
  glanced_wide <- dbdata$glanced |> select(-c(adj.r2, df.residual, null.deviance, df.null, deviance)) |> pivot_wider(names_from=c("model_number", "aggregate_base_model"), values_from = c("rsq", "nobs", "AIC", "BIC")) |>  rename(xvarname=xvar, yvarname=yvar)
  
  glanced_wide <- glanced_wide |> mutate(rsq_adjusted_base_diff=rsq_2_0-rsq_2_1, rsq_adjusted_diff = rsq_2_0-rsq_1_0) 
  
  expos_wide <- expos_wide |> left_join(glanced_wide |> select(-c(series, log_y, log_x, scaled_y, scaled_x)), by=c("xvarname", "yvarname", "x_table_name", "y_table_name"))
  expos_wide <- expos_wide |> left_join(dbdata$varnames, by=c("xvarname"="Variable.Name", "x_table_name"="Data.File.Name"))
  expos_wide <- expos_wide |> left_join(dbdata$varnames |> select(Variable.Name, Data.File.Name, Variable.Description, Data.File.Description), 
                                      by=c("yvarname"="Variable.Name", "y_table_name"="Data.File.Name"))

  expos_wide <- expos_wide |> collect() |> select(-Use.Constraints) |> rename(x_data_file_desc=Data.File.Description.x, y_data_file_desc=Data.File.Description.y,x_variable_description=Variable.Description.x, y_variable_description=Variable.Description.y)
  
  expos_wide_summary <- expos_wide |> filter(term == 'expo' | term == 'expo1' | term == 'expo2') |> group_by(xvarname, yvarname) |> summarize(mean_adjusted_base_r2_diff = mean(rsq_adjusted_base_diff), mean_unadjusted_r2_diff=mean(rsq_adjusted_diff), total_n = sum(nobs_2_0)) |> ungroup()

  
  
  adjusted_meta_full <- dbdata$adjusted_meta |> filter(model_number == 2) |> collect() |> left_join(expos_wide_summary, by=c("xvarname", "yvarname")) ## fully adjusted model
  adjusted_meta_raw <- dbdata$adjusted_meta |> filter(model_number == 1) |> collect() |> left_join(expos_wide_summary, by=c("xvarname", "yvarname")) 

  y_variable_domain <- dbdata$variable_domain |> filter(epcf == e_or_p) |> collect() |> group_by(Variable.Name) |> summarise(yvardesc=first(Variable.Description),ycategory=first(category),ysubcategory=first(subcategory))
  x_variable_domain <- dbdata$variable_domain |> filter(epcf == e_or_p) |> collect() |> group_by(Variable.Name) |> summarise(xvardesc=first(Variable.Description),xcategory=first(category),xsubcategory=first(subcategory))
  
  
  adjusted_meta_full <- adjusted_meta_full |> left_join(y_variable_domain, by=c("yvarname"="Variable.Name"))
  adjusted_meta_full <- adjusted_meta_full |> left_join(x_variable_domain, by=c("xvarname"="Variable.Name"))

  adjusted_meta_raw <- adjusted_meta_raw |> left_join(y_variable_domain, by=c("yvarname"="Variable.Name"))
  adjusted_meta_raw <- adjusted_meta_raw |> left_join(x_variable_domain, by=c("xvarname"="Variable.Name"))

  expos_wide <- expos_wide |> left_join(y_variable_domain, by=c("yvarname"="Variable.Name"))
  expos_wide <- expos_wide |> left_join(x_variable_domain, by=c("xvarname"="Variable.Name"))
  processed_data <- list(expos=expos, expos_wide=expos_wide, adjusted_meta_full=adjusted_meta_full, adjusted_meta_raw=adjusted_meta_raw, expos_wide=expos_wide, y_variable_domain=y_variable_domain, x_variable_domain=x_variable_domain, expos_wide_summary=expos_wide_summary, glanced_wide=glanced_wide) 
}


```


```{r}

#con <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_02_2024-v2.sqlite')
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_08_2024.sqlite')
pe_meta <- tbl(con, "pe_overall")
#pe <- get_data('../db/pe_summary_stats_02_2024-v2.sqlite')
pp <- get_data('../db/pp_summary_stats_03_2024.sqlite')
ee <- get_data('../db/ee_summary_stats_03_2024.sqlite')
pp_process <- process_data(pp, 'p')
ee_process <- process_data(ee, 'e')
```



# Distribution of the correlation globes

## Exposures
```{r distribution of all exposure correlations}
ee_process$adjusted_meta_raw <- ee_process$adjusted_meta_raw |> mutate(p.value_bonf = p.adjust(p.value, method="bonferroni"))
p <- ggplot(ee_process$adjusted_meta_raw |> filter(p.value_bonf < 0.05), aes(estimate))
p <- p + geom_histogram() + scale_x_continuous(limits=c(-1, 1))
p



```

## Phenotypes

```{r distribution of all phenotype correlations}
pp_process$adjusted_meta_raw <- pp_process$adjusted_meta_raw |> mutate(p.value_bonf = p.adjust(p.value, method="bonferroni"))
p <- ggplot(pp_process$adjusted_meta_raw |> filter(p.value_bonf < 0.05), aes(estimate))
p <- p + geom_histogram(aes(y = stat(density))) + scale_x_continuous(limits=c(-1, 1)) + facet_wrap(~ycategory)
p
```

## CDFs of correlation globes
```{r}
both_ee_pp <- rbind(
  ee_process$adjusted_meta_raw |> filter(p.value_bonf < 0.05) |> select(estimate) |> mutate(type="E-E"),
  pp_process$adjusted_meta_raw |> filter(p.value_bonf < 0.05) |> select(estimate) |> mutate(type="P-P")
)
p <- ggplot(both_ee_pp |> filter(estimate > 0), aes(estimate, color=type))
p <- p + stat_ecdf() + scale_x_continuous(limits=c(0, 1))
p <- p + theme_bw()
p
p <- ggplot(both_ee_pp |> filter(estimate < 0), aes(estimate, color=type))
p <- p + stat_ecdf() + scale_x_continuous(limits=c(-1, 0))
p <- p + theme_bw()
p


```


## Globe construction: choose those associated with a phenotype

```{r}
pe_sig <- pe_meta |> filter(term=='expo')
## bmi/a1c
pe_sig_cand <- pe_sig |> filter(phenotype == 'LBXGH', model_number==2, p.value < 1e-7)
```

## Construct the globe

```{r globe width, fig.height=7, fig.width=7}
E_CORR_THRESHOLD_NEG <- -0.2
E_CORR_THRESHOLD_POS <- 0.25

exposome_globe <- function(corr_tibble, exposure_tibble) {
  
  ff <- corr_tibble |> right_join(exposure_tibble |> select("exposure") |> collect(), by=c("xvarname"="exposure"))
  sig <- ff |> right_join(exposure_tibble |> select("exposure") |> collect(), by=c("yvarname"="exposure")) 

  sig_to_plot <- sig |> filter(estimate > E_CORR_THRESHOLD_POS | estimate < E_CORR_THRESHOLD_NEG) ## filter among the highest correlations -- choose some background distribution

  sig_graph <- sig_to_plot |> select(-term_name) |> select(xvarname, yvarname, everything()) 
  sig_vertex <- sig_graph |> select(xvarname, xcategory) |> unique() |> rename(varname = xvarname, category=xcategory)
  sig_vertex2 <- sig_graph |> select(yvarname, ycategory) |> unique() |> rename(varname = yvarname, category=ycategory)
  sig_vertex <- sig_vertex |> rbind(sig_vertex2) |> unique()
  sig_graph <- sig_graph |> mutate(estimate = ifelse(estimate > 1, 1, estimate)) |> mutate(estimate = ifelse(estimate < 1, -1, estimate))

  g <- graph_from_data_frame(sig_graph, directed = FALSE) 
  E(g)$color <- ifelse(E(g)$estimate > 0, "black", "grey")
  V(g)$category <- sig_vertex$category[match(V(g)$name, sig_vertex$varname)]
  categories <- unique(V(g)$category)
  # Assign colors to each category
  color_pal <- ggsci::pal_tron("legacy", alpha = 0.7)
  category_colors <- setNames(color_pal(length(categories)), categories)
  # Map the colors to vertices based on category
  vertex_colors <- category_colors[V(g)$category]
  coords <- layout_in_circle(g)
  scaling_factor <- 1
  plot(g, vertex.color = vertex_colors, layout=coords,
     vertex.size = 10,
     vertex.color = vertex_colors,
     vertex.label = substr(V(g)$name, nchar(V(g)$name)-2, nchar(V(g)$name)),      # Label each vertex with its name
     vertex.label.cex = 0.7,         # Control the size of the labels
     vertex.label.color = "black",   # Color of the labels
    vertex.label.family = "sans",
    edge.width = abs(E(g)$estimate) * scaling_factor)
}


exposome_globe(ee_process$adjusted_meta_raw, pe_sig |> filter(phenotype == 'LBXGH', model_number==2, p.value < 1e-7))
exposome_globe(ee_process$adjusted_meta_raw, pe_sig |> filter(phenotype == 'LBXGLU', model_number==2, p.value < 1e-7))
exposome_globe(ee_process$adjusted_meta_raw, pe_sig |> filter(phenotype == 'LBXCRP', model_number==2, p.value < 1e-7))
exposome_globe(ee_process$adjusted_meta_raw, pe_sig |> filter(phenotype == 'BMXBMI', model_number==2, p.value < 1e-15))

```



```{r write out globe}

ee_corrs <- ee_process$adjusted_meta_raw |> select(xvarname, xvardesc, yvarname, yvardesc, estimate, p.value, p.value_bonf, std.error, xcategory, xsubcategory, ycategory, ysubcategory, model_number, mean_adjusted_base_r2_diff, mean_unadjusted_r2_diff)
pp_corrs <- pp_process$adjusted_meta_raw |> select(xvarname, xvardesc, yvarname, yvardesc, estimate, p.value, p.value_bonf, std.error, xcategory, xsubcategory, ycategory, ysubcategory, model_number, mean_adjusted_base_r2_diff, mean_unadjusted_r2_diff)
write_rds(ee_corrs, "ee_corrs.rds")
write_rds(pp_corrs, "pp_corrs.rds")
dbDisconnect(con)
```
