---
title: "Multiyear test"
author: "Chirag Patel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r start anew}
if(exists("con")) {
  dbDisconnect(con)
  remove(list=ls())
}

```

```{r}
library(tidyverse)
library(DBI)
library(survey)
library(tictoc)
devtools::load_all("..")
```

```{r connect}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/nhanes_012324.sqlite')
varnames <- dplyr::tbl(con, "variable_names_epcf") |> collect()

```

```{r testing code}
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/nhanes_012324.sqlite')
## get LBXBEC tables
varnames <- dplyr::tbl(con, "variable_names_epcf") |> collect()
varnames |> filter(Variable.Name == 'LBXBEC') |> select(Data.File.Name)
bec_b <- tbl(con, "L06VIT_B") |> select(c(SEQN, LBXBEC)) |> collect()
bec_c <- tbl(con, "L45VIT_C") |> select(c(SEQN, LBXBEC)) |> collect()
bec_d <- tbl(con, "VITAEC_D") |> select(c(SEQN, LBXBEC)) |> collect()
bec_j <- tbl(con, "VITAEC_J") |> select(c(SEQN, LBXBEC)) |> collect()
bec <- rbind(bec_b, bec_c, bec_d, bec_j)

varnames |> filter(Variable.Name == 'LBXGLU') |> select(Data.File.Name)

glu_b <- tbl(con, "L10AM_B") |> select(c(SEQN, LBXGLU, WTSAF2YR)) |> collect()
glu_c <- tbl(con, "L10AM_C") |> select(c(SEQN, LBXGLU, WTSAF2YR)) |> collect()
glu_d <- tbl(con, "GLU_D") |> select(c(SEQN, LBXGLU, WTSAF2YR)) |> collect()
glu_j <- tbl(con, "GLU_J") |> select(c(SEQN, LBXGLU, WTSAF2YR)) |> collect()
glu <- rbind(glu_b, glu_c, glu_d, glu_j)

demo_cols <- c("SEQN", "SDDSRVYR", "RIDAGEYR", "RIAGENDR", "AGE_SQUARED", "WTMEC2YR", "SDMVPSU", "SDMVSTRA", "RIDRETH1", "INDFMPIR", "ETHNICITY_NONHISPANICWHITE", "ETHNICITY_MEXICAN","ETHNICITY_OTHERHISPANIC", "ETHNICITY_OTHER", "EDUCATION_LESS9", "EDUCATION_9_11", "EDUCATION_COLLEGEGRAD", "EDUCATION_HSGRAD", "ETHNICITY_NONHISPANICBLACK")
#adjustmentVariables <- c("RIDAGEYR", "AGE_SQUARED",
#                         "RIAGENDR",
#                         "INDFMPIR",
#                         "EDUCATION_LESS9","EDUCATION_9_11","EDUCATION_AA","EDUCATION_COLLEGEGRAD",
#                         "ETHNICITY_MEXICAN", "ETHNICITY_OTHERHISPANIC","ETHNICITY_OTHER", #"ETHNICITY_NONHISPANICBLACK")


demo_b <- tbl(con, "DEMO_B") |> select(all_of(demo_cols))  |> collect() 
demo_c <- tbl(con, "DEMO_C") |> select(all_of(demo_cols)) |> collect()
demo_d <- tbl(con, "DEMO_D") |> select(all_of(demo_cols)) |> collect()
demo_j <- tbl(con, "DEMO_J") |> select(all_of(demo_cols)) |> collect()

demo <- rbind(demo_b, demo_c, demo_d, demo_j)

bind_tables <- function(con, table_name_list) {
  tables <- vector(mode="list", length=length(table_name_list))
  for(t in 1:length(table_name_list)) {
    tables[[t]] <- dplyr::tbl(con, table_name_list[t]) |> collect()
  }
  deep_table <- bind_rows(tables)
}


demo <- bind_tables(con, c("DEMO_B", "DEMO_C", "DEMO_D", "DEMO_J"))
glu <- bind_tables(con, c("L10AM_B", "L10AM_C", "GLU_D", "GLU_J"))
bec <- bind_tables(con, c("L06VIT_B", "L45VIT_C", "VITAEC_D", "VITAEC_J"))

glu_bec <- demo |> left_join(bec, by="SEQN") |> left_join(glu, by="SEQN")
glu_bec <- glu_bec |> mutate(wt = WTSAF2YR/4)
glu_bec <- glu_bec |> filter(!is.na(wt), wt > 0)

dsn <- svydesign(ids=~SDMVPSU, strata = ~SDMVSTRA, weights=~wt, data=glu_bec, nest=T)

mod <- svyglm(I(scale(log(LBXGLU))) ~ scale(log(LBXBEC)) + 
                RIDAGEYR + RIAGENDR + AGE_SQUARED +
                ETHNICITY_OTHER + ETHNICITY_OTHERHISPANIC + 
                ETHNICITY_MEXICAN + ETHNICITY_NONHISPANICBLACK + 
                INDFMPIR
              , dsn)

summary(mod)
summary(mod, df.resid=Inf)

```

       Estimate Std. Error t value Pr(>|t|)    
(Intercept)                -4.611e-01  4.878e-02  -9.452 8.51e-13 ***
scale(log(LBXBEC))         -1.335e-01  1.549e-02  -8.622 1.57e-11 ***
RIDAGEYR                    2.058e-02  2.163e-03   9.512 6.91e-13 ***
RIAGENDR                   -2.399e-01  2.256e-02 -10.637 1.50e-14 ***
AGE_SQUARED                -2.395e-05  2.213e-05  -1.082   0.2842    
ETHNICITY_OTHER             2.143e-01  4.785e-02   4.478 4.26e-05 ***
ETHNICITY_OTHERHISPANIC     1.820e-01  7.885e-02   2.308   0.0251 *  
ETHNICITY_MEXICAN           2.629e-01  4.221e-02   6.229 8.96e-08 ***
ETHNICITY_NONHISPANICBLACK  1.430e-02  3.729e-02   0.383   0.7030    
INDFMPIR                   -1.017e-02  6.975e-03  -1.458   0.1508    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for gaussian family taken to be 0.7238453)

Number of Fisher Scoring iterations: 2


```{r}

jack <- get_multiyear_x_y_tables(con, 
                                 c("L10AM_B", "L10AM_C", "GLU_D", "GLU_J"), 
                                 c("L06VIT_B", "L45VIT_C", "VITAEC_D", "VITAEC_J")
                                 )
jack$p_table <- jack$table1
jack$e_table <- jack$table2


jack2 <- get_multiyear_x_y_tables(con, 
                                  c("LAB10AM", "L10AM_B"),
                                  c("DRXTOT", "DRXTOT_B")
                                  )
jack2$p_table <- jack2$table1
jack2$e_table <- jack2$table2

jack3 <- get_multiyear_x_y_tables(con, 
                                  c("LAB10AM", "L10AM_B", "L10AM_C"),
                                  c("DRXTOT", "DRXTOT_B", "DR1TOT_C")
                                  )
jack3$p_table <- jack3$table1
jack3$e_table <- jack3$table2

jack4 <- get_multiyear_x_y_tables(con, 
                                  c("LAB10AM", "L10AM_B", "L10AM_C", "GLU_D"),
                                  c("DRXTOT", "DRXTOT_B", "DR1TOT_C", "DR1TOT_D")
                                  )
jack4$p_table <- jack4$table1
jack4$e_table <- jack4$table2


#jackson <- figure_out_weight(jack)
jackson <-  figure_out_multiyear_weight(jack)
dsn <- xysvydesign(jackson)
mod <- svyglm(I(scale(log(LBXGLU))) ~ scale(log(LBXBEC)) + 
                RIDAGEYR + RIAGENDR + AGE_SQUARED +
                ETHNICITY_OTHER + ETHNICITY_OTHERHISPANIC + 
                ETHNICITY_MEXICAN + ETHNICITY_NONHISPANICBLACK + 
                INDFMPIR
              , dsn)

test <- pe_by_table(tab_obj = jackson, pvar = "LBXGLU", evar = "LBXBEC",  adjustment_variables = adjustmentVariables, scale_p = T) ## works

test <- pe_by_table_flex_adjust(jackson, pvar = "LBXGLU", evar = "LBXBEC", adjustment_models, scale_p = T) ## works
test2 <- pe("BMXBMI", "LBXBCD", adjustmentVariables, 'F', con, scale_p = T)
devtools::load_all("..")
#jack2 <- pe2("BMXBMI", "LBXBCD", adjustmentVariables, con)

tic()
jack <- pe_flex_adjust("BMXBMI", "LBXBCD", adjustment_models, con, scale_p=T)
toc()

jack <- pe_flex_adjust("BMXBMI", "LBXBCD", adjustment_models, con, scale_p=T)
jack2 <- pe_flex_adjust("LBXCRP", "LBXGTC", adjustment_models, con, scale_p=T)
```
