---
title: "Quickstart: Associating a phenotype with an exposure"
author: "Chirag Patel"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r start anew}
if(exists("con")) {
  dbDisconnect(con)
  remove(list=ls())
}

```

# Estimating an association between an exposure and phenotype across multiple years


```{r}
library(tidyverse)
library(DBI)
library(survey)
devtools::load_all(".")
```

```{r connect}
#con <- DBI::dbConnect(RSQLite::SQLite(), dbname='./db/nhanes_012324.sqlite')
#con <- DBI::dbConnect(RSQLite::SQLite(), dbname='./db/nhanes_112824.sqlite')
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='./db/nhanes_031725.sqlite')
varnames <- dplyr::tbl(con, "variable_names_epcf") 
```



# C-Reactive Protein (P) and Cotinine (E)
```{r serum cotinine and c-reactive protein}
varnames |> filter(Variable.Name == 'LBXCOT')
varnames |> filter(Variable.Name == 'LBXCRP')
crp_cot <- pe_flex_adjust("LBXCRP", "LBXCOT", adjustment_models, con, scale_p=T, logxform_p = F, scale_type=3)
# print out the tidied summary stats for the fully adjusted model
crp_cot$models[[2]]$tidied
# R2 for the full adjusted model
crp_cot$models[[2]]$r2
# R2 for base model
crp_cot$base_models[[2]]$r2
# full-base
crp_cot$models[[2]]$r2$rsq - crp_cot$base_models[[2]]$r2$rsq
```

# GH(P) and gamma-tocopherol (E)
```{r serum cotinine and c-reactive protein}
gh_gtc <- pe_flex_adjust("LBXGH", "LBXGTC", adjustment_models, con, scale_p=T, logxform_p = F, scale_type=3)
# 0.1104320348
# print out the tidied summary stats for the fully adjusted model
gh_gtc$models[[2]]$tidied
# R2 for the full adjusted model
gh_gtc$models[[2]]$r2
# R2 for base model
gh_gtc$base_models[[2]]$r2
# full-base
gh_gtc$models[[2]]$r2$rsq - crp_cot$base_models[[2]]$r2$rsq
```

Age?
```{r}
ptables <- get_table_names_for_varname(con, varname = "RIDAGEYR") |> rename(p_name = Data.File.Name)
etables <- get_table_names_for_varname(con, varname = "LBXCOT") |> rename(e_name = Data.File.Name)
table_set <- ptables |> inner_join(etables, by = "Begin.Year")
tab_obj <- get_x_y_tables_as_list(con,table_set$p_name,table_set$e_name)
tab_obj <- tab_obj |> figure_out_multiyear_weight()
age_cot <- pe_flex_adjust("RIDAGEYR", "LBXCOT", adjustment_models |> filter(scenario=="base"), con, scale_p=T)
```

Lead and RDW
```{r}


test_scenario <- adjustment_models |> filter(scenario == 'age_sex_ethnicity_income_education')

test_scenario <- test_scenario |> 
  rbind(tibble(scenario = 'age_sex_ethnicity_income_education', variables='as.factor(SDDSRVYR)', domain='default'))

rdw_bpb <- pe_flex_adjust("LBXRDW", "LBXBPB", test_scenario, con, scale_p=T, scale_e = T, logxform_e = T)

#rdw_bpb <- pe_flex_adjust("LBXRDW", "LBXCOT", test_scenario, con, scale_p=T, scale_e = T, logxform_e = T)


ptables <- get_table_names_for_varname(con, varname = "LBXRDW") |> rename(p_name = Data.File.Name)
etables <- get_table_names_for_varname(con, varname = "LBXBPB") |> rename(e_name = Data.File.Name)
table_set <- ptables |> inner_join(etables, by = "Begin.Year")
if(nrow(table_set) == 0) {
    stop("Y and X variables not collected in the same survey")
}


  ## get table names for each series
tab_obj <- get_x_y_tables_as_list(con,table_set$p_name,table_set$e_name)
tab_obj <- tab_obj |> figure_out_multiyear_weight()

```

fatty acid and LBXIN
```{r}
test_scenario <- adjustment_models |> filter(scenario == 'age_sex_ethnicity_income_education')

test_scenario <- test_scenario |> 
  rbind(tibble(scenario = 'age_sex_ethnicity_income_education', variables='as.factor(SDDSRVYR)', domain='default'),
        tibble(scenario = 'age_sex_ethnicity_income_education', variables='BMXBMI_adj', domain='default')
        )
in_fa <- pe_flex_adjust("LBXIN", "LBXOD9", test_scenario, con, scale_p=T, scale_e = T, logxform_e = T)

```


# Explore the uBiome and alpha diversity

```{r}
varnames |> filter(Variable.Name == 'RB_family1_count')

rb_count <- tbl(con, 'DADA2RB_FAMILY_COUNT_F')
alpha <- tbl(con, 'ALPHADIVERSITY_F')

rb_count |> colnames()

rb_count |> collect() |> str() ## which ones actually have variation?

p <- ggplot(rb_count, aes((RB_family29_count+.01))) ## looks like it is right skewed
p + geom_histogram()

```

#  RB_family1_count (P) and Cotinine (E)
```{r serum cotinine and RB29 count}

varnames |> filter(Variable.Name == 'LBXCOT') # indicator of nicotene (smoke exposure)
varnames |> filter(Variable.Name == 'RB_family29_count') # Actinomycetaceae
rb_cot <- pe_flex_adjust("RB_family29_count", "LBXCOT", adjustment_models, con, scale_p=T, logxform_p = T)
# print out the tidied summary stats for the fully adjusted model
rb_cot$models[[2]]$tidied
# R2 for the full adjusted model
rb_cot$models[[2]]$r2
# R2 for base model
rb_cot$base_models[[2]]$r2
# full-base
rb_cot$models[[2]]$r2$rsq - rb_cot$base_models[[2]]$r2$rsq
```


# Urinary Creatinine and Urinary Chlamydia: positive and negative test
```{r urinary creatinine}
varnames |> filter(Variable.Name == 'URXUCL')
ucr_ucl <- pe_flex_adjust("URXUCR", "URXUCL", adjustment_models, con, scale_p=T, scale_e=F, logxform_e = F, exposure_levels = c(1,2))
ucr_ucl$models[[2]]$tidied
```

```{r disconnect}
dbDisconnect(con)
```
