---
title: "Create Database for Shiny App"
author: "Chirag Patel"
date: "2024-12-30"
output: html_document
---


```{r}
library(tidyverse)
library(DBI)
```

```{r}
#con <- DBI::dbConnect(RSQLite::SQLite(), dbname='./pe_summary_stats_08_2024.sqlite')
con <- DBI::dbConnect(RSQLite::SQLite(), dbname='./pe_summary_stats_01_2025.sqlite')
varnames <- tbl(con, "variable_names_epcf")
adjusted_meta <- tbl(con, "adjusted_meta_uwls") |> rename(term_name=expo_name)
mvr2 <- read_rds('../pe_summary_060623/mvr2.rds') |> mutate(mv = mve_rsq-base_rsq)
pe <- tbl(con, "pe") ## individual surveys
pe_r2 <- tbl(con, "rsq")
glanced <- tbl(con, "glanced")
glanced <- glanced |> left_join(pe_r2 |> select(exposure, phenotype, series, model_number,aggregate_base_model, rsq, adj.r2), by=c("exposure", "phenotype", "model_number", "aggregate_base_model", "series"))
variable_domain <- tbl(con, "variable_domain")
pe_overall <- tbl(con, "pe_overall")
r2_overall <- tbl(con, "rsq_overall")
glanced_overall <- tbl(con, "glanced_overall")
glanced_overall <- glanced_overall |> left_join(r2_overall |> select(exposure, phenotype, model_number,aggregate_base_model, rsq, adj.r2), by=c("exposure", "phenotype", "model_number", "aggregate_base_model"))

```


```{r}
expos <- pe |> filter(term %like% 'expo%') |> rename(evarname=exposure, pvarname=phenotype)
expos_wide <- expos |> pivot_wider(names_from = "model_number", values_from = c("estimate", "std.error", "statistic", "p.value")) 
glanced_wide <- glanced |> select(-c(adj.r2, df.residual, null.deviance, df.null, deviance)) |> pivot_wider(names_from=c("model_number", "aggregate_base_model"), values_from = c("rsq", "nobs", "AIC", "BIC")) |>  rename(evarname=exposure, pvarname=phenotype)
glanced_wide <- glanced_wide |> mutate(rsq_adjusted_base_diff=rsq_2_0-rsq_2_1, rsq_adjusted_diff = rsq_2_0-rsq_1_0) 
glanced_overall_wide <- glanced_overall |> select(-c(adj.r2, df.residual, null.deviance, df.null, deviance)) |> pivot_wider(names_from=c("model_number", "aggregate_base_model"), values_from = c("rsq", "nobs", "AIC", "BIC")) |>  rename(evarname=exposure, pvarname=phenotype)

expos_wide <- expos_wide |> left_join(glanced_wide |> select(-c(series, log_p, log_e, scaled_p, scaled_e)), by=c("evarname", "pvarname", "exposure_table_name", "phenotype_table_name"))
expos_wide <- expos_wide |> left_join(varnames, by=c("evarname"="Variable.Name", "exposure_table_name"="Data.File.Name"))
expos_wide <- expos_wide |> left_join(varnames |> select(Variable.Name, Data.File.Name, Variable.Description, Data.File.Description), 
                                      by=c("pvarname"="Variable.Name", "phenotype_table_name"="Data.File.Name"))

expos_wide <- expos_wide |> collect() |> select(-Use.Constraints) |> rename(e_data_file_desc=Data.File.Description.x, p_data_file_desc=Data.File.Description.y,e_variable_description=Variable.Description.x, p_variable_description=Variable.Description.y)


glanced_summary <- glanced_overall_wide |> mutate(total_n = nobs_2_0, rsq_adjusted_base_diff = rsq_2_0-rsq_2_1, rsq_adjusted_diff=rsq_2_0-rsq_1_0) |> 
  select(evarname, pvarname, rsq_adjusted_base_diff, rsq_adjusted_diff, total_n)

adjusted_meta_full <- adjusted_meta |> filter(model_number == 2)  |> left_join(glanced_summary, by=c("evarname", "pvarname")) |> collect() ## fully adjusted model

p_variable_domain <- variable_domain |> filter(epcf == 'p') |> collect() |> group_by(Variable.Name) |> summarise(pvardesc=first(Variable.Description),pcategory=first(category),psubcategory=first(subcategory))
e_variable_domain <- variable_domain |> filter(epcf == 'e') |> collect() |> group_by(Variable.Name) |> summarise(evardesc=first(Variable.Description),ecategory=first(category),esubcategory=first(subcategory))

adjusted_meta_full <- adjusted_meta_full |> left_join(p_variable_domain, by=c("pvarname"="Variable.Name"))
adjusted_meta_full <- adjusted_meta_full |> left_join(e_variable_domain, by=c("evarname"="Variable.Name"))
expos_wide <- expos_wide |> left_join(p_variable_domain, by=c("pvarname"="Variable.Name"))
expos_wide <- expos_wide |> left_join(e_variable_domain, by=c("evarname"="Variable.Name"))
mvr2 <- mvr2 |> collect() |> left_join(p_variable_domain, by=c("pvarname"="Variable.Name"))

pe_overall_full <- pe_overall |> filter(model_number == 2, term %like% "expo%") |> select(term, estimate, std.error, statistic, p.value, exposure, phenotype) |> 
  rename(evarname = exposure, pvarname = phenotype, term_name=term) |> collect()

adjusted_meta_full <- adjusted_meta_full |> left_join(pe_overall_full, by=c("term_name", "evarname", "pvarname"), suffix=c("", "_overall"))

adjusted_meta_full <- adjusted_meta_full |> mutate(estimate_overall=ifelse(k.uwls == 1, estimate.uwls, estimate), 
                                                   p.value_overall=ifelse(k.uwls == 1, p.value.uwls, p.value),
                                                   std.error_overall=ifelse(k.uwls == 1, std.error.uwls, std.error), 
                                                   statistic_overall=ifelse(k.uwls == 1, statistic.uwls, statistic)
                                                   )
```
```{r filter exposure categories}
exposure_categories <- c("pollutant", "nutrients", "smoking", "infection")
adjusted_meta_full <- adjusted_meta_full |> filter(ecategory %in% exposure_categories)
expos_wide <- expos_wide |> filter(ecategory %in% exposure_categories)

```

```{r}
# Keep number of surveys is greater than 2
adjusted_meta_full <- adjusted_meta_full |> mutate(nobs = k.uwls)
adjusted_meta_2 <- adjusted_meta_full |> filter(nobs >= 2)
```

```{r}
adjusted_meta_2 <- adjusted_meta_2 |> filter(!is.na(estimate_overall), !is.na(p.value_overall))
adjusted_meta_2 <- adjusted_meta_2 |> ungroup() |>  mutate(pval_BY=p.adjust(p.value_overall, method="BY"), pvalue_bonferroni=p.adjust(p.value_overall, method="bonferroni"))
adjusted_meta_2 <- adjusted_meta_2 |> mutate(sig_levels = case_when(
  pvalue_bonferroni < 0.05 ~ 'Bonf.<0.05',
  pval_BY < 0.05 ~ 'BY<0.05',
  TRUE ~ '> BY & Bonf.'
))
```

```{r}
adjusted_meta_2 <- adjusted_meta_2 |> mutate(
  pnewsubcategory =  case_when(
    psubcategory == 'injury' ~ "inflammation",
    psubcategory == 'liver/kidney' ~ "kidney",
    psubcategory == 'immunity' ~ "liver",
    psubcategory == 'exhaled NO' ~ "inflammation",
    psubcategory == 'lung function' ~ "lung",
    psubcategory == 'nutritional status' ~ "nutrition",
    TRUE ~ psubcategory
  )
)

adjusted_meta_2 <- adjusted_meta_2 |> mutate(pnewsubcategory = ifelse(is.na(pnewsubcategory), pcategory, pnewsubcategory))
adjusted_meta_2 <- adjusted_meta_2 |> mutate(enewsubcategory = ifelse(ecategory == 'infection', 'infection', esubcategory))
adjusted_meta_2 <- adjusted_meta_2 |> mutate(enewsubcategory = ifelse(enewsubcategory == 'pyrethoid', 'pyrethroid', enewsubcategory)) 
adjusted_meta_2 <- adjusted_meta_2 |> mutate(enewsubcategory = ifelse(enewsubcategory == 'amine' | enewsubcategory == 'amide', 'amine/amide', enewsubcategory))
adjusted_meta_2 <- adjusted_meta_2 |> mutate(enewsubcategory = ifelse(enewsubcategory == 'deet', 'amine/amide', enewsubcategory))


```

```{r quantile data}
load_quantile_data <- function(con_q) {
  #con_q_ns  <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_percentile_noscale_p_10_2024.sqlite')
  pe_overall_q <- tbl(con_q, "pe_overall")
  pe_quantile <- pe_overall_q |> filter( model_number == 2) |> filter(term == 'expoq2' | term =='expoq3' | term == 'expoq4' | term=='expoq5') |> collect()
  

  pe_quantile <- pe_quantile |> rename(evarname=exposure, pvarname=phenotype)
  pe_quantile <- pe_quantile |> mutate(exposure_level = case_when(
  term == 'expoq2' ~ 'Q[25-50)',
  term == 'expoq3' ~ 'Q[50-75)',
  term == 'expoq4' ~ 'Q[75-90)',
  term == 'expoq5' ~ 'Q[90-100)',
  TRUE ~ NA_character_
  ))
  linear_res <- adjusted_meta_2 |> filter(term_name == 'expo') |> select(evarname, pvarname, estimate_overall, sig_levels, ecategory, esubcategory, pcategory, psubcategory, enewsubcategory, pnewsubcategory)

  pe_quantile_all <- pe_quantile |> left_join(linear_res, by=c("evarname", "pvarname"))
  return(pe_quantile_all)
}

#con_q  <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_percentile_10_2024.sqlite')
con_q  <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_percentile_scale_p_01_2025_v2.sqlite')
pe_quantile_all <- load_quantile_data(con_q)
dbDisconnect(con_q)
#con_q  <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_percentile_noscale_p_10_2024.sqlite')
con_q  <- DBI::dbConnect(RSQLite::SQLite(), dbname='../db/pe_summary_stats_percentile_noscale_p_01_2025_v2.sqlite')
pe_quantile_ns <- load_quantile_data(con_q)
dbDisconnect(con_q)
pe_quantile_ns |> filter(pvarname == 'LBXGLU', evarname=='LBXGTC')

```

```{r}
enewsubcategory_labels <- c("DI",
                            "OR",
                            "DB",
                            "VO",
                            "PP",
                            "HM",
                            "HY",
                            "DA",
                            "PH",
                            "AA",
                            "SB",
                            "PT",
                            "PO",
                            "IN", "SU", "SM")
names(enewsubcategory_labels) <- c("dietary interview",
                                   "organochlorine",
                                   "dietary biomarker",
                                   "VOC",
                                   "priority pesticide",
                                   "heavy metals",
                                   "hydrocarbon",
                                   "diakyl",
                                   "phenols",
                                   "amine/amide",
                                   "smoking biomarker",
                                   "phthalates",
                                   "polyfluoro",
                                   "infection",
                                   "supplements",
                                   "smoking behavior" )
```

```{r average across e p}


e_summary <- adjusted_meta_2 |> group_by(evarname) |> arrange(pvalue_bonferroni) |>  
  summarize(mean_r2=mean(rsq_adjusted_base_diff, na.rm=T),  mean_estimate=mean(abs(estimate), na.rm=T), 
            median_pvalue=median(p.value, na.rm=T), n_sig=sum(pvalue_bonferroni < 0.05, na.rm=T), 
            n_tests=sum(!is.na(pvalue_bonferroni)),  median_i.squared=median(i.squared.uwls, na.rm=T),
            max_r2=first(rsq_adjusted_base_diff), max_pvarname=first(pvarname) , max_estimate=first(estimate), max_p.value=first(p.value)) |> mutate(n_sig_pct=n_sig/n_tests)


p_summary <- adjusted_meta_2 |> group_by(pvarname) |> arrange(pvalue_bonferroni) |> 
  summarize(mean_r2=mean(rsq_adjusted_base_diff, na.rm=T), mean_estimate=mean(abs(estimate), na.rm=T),
            median_pvalue=median(p.value, na.rm=T), n_sig=sum(pvalue_bonferroni < 0.05, na.rm=T), 
            n_tests=sum(!is.na(pvalue_bonferroni)),  median_i.squared=median(i.squared.uwls, na.rm=T),
            max_r2=first(rsq_adjusted_base_diff), max_evarname=first(evarname) , max_estimate=first(estimate), max_p.value=first(p.value)) |> mutate(n_sig_pct=n_sig/n_tests)

## deeper summary by group

p_group_summary <- adjusted_meta_2 |> unite(p_scategory, c(pcategory, psubcategory)) |> group_by(p_scategory) |> arrange(pvalue_bonferroni) |>  
  summarize(mean_r2=mean(rsq_adjusted_base_diff, na.rm=T),  mean_estimate=mean(abs(estimate), na.rm=T), 
            median_pvalue=median(p.value, na.rm=T), n_sig=sum(pvalue_bonferroni < 0.05, na.rm=T), 
            n_tests=sum(!is.na(pvalue_bonferroni)),  median_i.squared=median(i.squared.uwls, na.rm=T),
            max_r2=first(rsq_adjusted_base_diff), max_evarname=first(evarname) , max_estimate=first(estimate), max_p.value=first(p.value)) |> mutate(n_sig_pct=n_sig/n_tests)


e_group_summary <- adjusted_meta_2 |> unite(e_scategory, c(ecategory, esubcategory)) |> group_by(e_scategory) |> arrange(pvalue_bonferroni) |>  
  summarize(mean_r2=mean(rsq_adjusted_base_diff, na.rm=T),  
            mean_abs_estimate=mean(abs(estimate), na.rm=T),
            mean_estimate=mean((estimate), na.rm=T),
            median_pvalue=median(p.value, na.rm=T), 
            n_sig=sum(pvalue_bonferroni < 0.05, na.rm=T), 
            n_tests=sum(!is.na(pvalue_bonferroni)),  
            median_i.squared=median(i.squared.uwls, na.rm=T),
            max_r2=first(rsq_adjusted_base_diff), 
            max_pvarname=first(pvarname), 
            max_estimate=first(estimate), max_p.value=first(p.value)) |> mutate(n_sig_pct=n_sig/n_tests)



```

```{r globes}
ee <- read_rds('../rmd/ee_corrs.rds')
pp <- read_rds('../rmd/pp_corrs.rds')
```

```{r LD score correlation}
library(corrr)
to_array <- adjusted_meta_2 |> filter(term_name == 'expo') |>
  select(evarname, pvarname, estimate, p.value) |> mutate(estimate= ifelse(p.value >= 0.05, 0, estimate)) |>
  mutate(estimate = ifelse(is.na(estimate), 0, estimate))  |> select(-p.value) |> pivot_wider(names_from = pvarname, values_from = estimate)
exposure_correlation <- to_array |> select(-evarname) |> correlate(diagonal = 1) |> stretch(na.rm = TRUE, remove.dups = TRUE)

to_array <- adjusted_meta_2 |> filter(term_name == 'expo') |> select(evarname, pvarname, estimate, p.value) |> mutate(estimate= ifelse(p.value >= 0.05, 0, estimate)) |> mutate(estimate = ifelse(is.na(estimate), 0, estimate))  |> select(-p.value) |> pivot_wider(names_from = evarname, values_from = estimate)
phenome_correlation <- to_array |> select(-pvarname) |> correlate(diagonal = 1) |> stretch(na.rm = TRUE, remove.dups = TRUE)
```

```{r}
shiny_con <-  DBI::dbConnect(RSQLite::SQLite(), dbname='../pe_atlas_app/pe_shiny_2.sqlite')

dbWriteTable(shiny_con, 'p_variable_domain', p_variable_domain, temporary=F, overwrite=T) # done 
dbWriteTable(shiny_con, 'e_variable_domain', e_variable_domain, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'exposure_correlation', exposure_correlation, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'phenotype_correlation', phenome_correlation, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'e_group_summary', e_group_summary, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'e_summary', e_summary, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'p_group_summary', p_group_summary, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'p_summary', p_summary, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'adjusted_meta_2', adjusted_meta_2, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'expos_wide', expos_wide, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'ee', ee, temporary=F, overwrite=T) # done
dbWriteTable(shiny_con, 'pe_quantile_all', pe_quantile_all, temporary = F, overwrite=T )
dbWriteTable(shiny_con, 'pe_quantile_ns', pe_quantile_ns, temporary=F, overwrite=T)
dbDisconnect(shiny_con)
dbDisconnect(con)
```
